local function DisableAllCameras()
	for i = 1, 3 do
	Game.DisableTrigger("bm_cam" .. i)
	end
end

local function EnableCamera(tableIndex)
	local CamToDisable = {1,2,3}
	table.remove(CamToDisable, tableIndex)
	for i, cam in ipairs(CamToDisable) do
		Game.DisableTrigger("bm_cam" .. cam)
	end
end

local function SurviveConditionsInstant()
	Game.AddCondition("damage")
		Game.SetCondMinHealth(0.0)
		Game.SetCondTargetVehicle("current")
	Game.CloseCondition()
	Game.AddCondition("outofvehicle")
		Game.SetCondTime(-1000)
		Game.SetCondTargetVehicle("current")
	Game.CloseCondition()
end

Game.SelectMission("bm1")
	--Game.SetMissionResetPlayerOutCar("bm1_apu_sd", "bm_carstart")
	Game.SetMissionResetPlayerOutCar("bm_apu_restart", "bm_carstart")
	--Game.SetMissionResetPlayerInCar("bm_carstart")
	Game.SetDynaLoadData("l5z2.p3d;l5r1.p3d;l5r2.p3d;")

	Game.UsePedGroup(0)
	Game.SetNumValidFailureHints( Mode.FailHintCount )

	if Flags.BMLoadBarricades then
		Game.StreetRacePropsLoad("l1m1_baracade.p3d;")
		--Game.StreetRacePropsUnload("l1m1_baracade.p3d:")	--disappears then reappears in a split second.
		
		Game.SetPedsEnabled(1)
		Game.SetParkedCarsEnabled(1)
	end

	Game.SetNumValidFailureHints( Mode.FailHintCount )
	
	if GetSetting("ScrapBookMode") then
		Game.AddStage(0)
			DisableAllCameras()
			Game.AddObjective("timer")
				Game.AddNPC("apu", "bm_hide_npc")
				Game.SetDurationTime(0.2)
			Game.CloseObjective()
			Game.SetMusicState("BonusMission", "Bonus")
		Game.CloseStage()
		
		Game.AddStage(0)
			EnableCamera(1)
			Game.ResetStageHitAndRun()
			Game.NoTrafficForStage()
			Game.AddStageCharacter("bart", "bm_player_cam1", "", "current", "bm_hide_car")
			Game.AddStageVehicle("kwik_v", "bm_kwik_end", "NULL", "Missions/level01/kwik_vBM.con")
			Game.AddObjective("dummy")
				Game.AddDriver("apu", "kwik_v")
				Game.AddNPC("bart2", "bm_bart_end")
			Game.CloseObjective()
		Game.CloseStage()
		Game.CloseMission()
		return
	end
	
	--player can ruin ending cutscene here by driving player vehicle in the way, getting into traffic car, then playing ending
	Game.AddStage(0)
		Game.RESET_TO_HERE()
		DisableAllCameras()
		Game.SetStageMessageIndex(12)
		--Game.SetStageCharacterModel("apu", "apu")	--HEY LUCAS. this causes crash when reverting back to original character with non-default costumes. this happened in AS L1 and SLEM 1.0 too.
		Game.SetStageCharacterModel("apu")	--needed for every stage
		Game.AddObjective("getin")
			Game.AddNPC("apu", "bm_hide_npc")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
		Game.SetMusicState("BonusMission", "Bonus")
	Game.CloseStage()
	
	Game.AddStage(0)
		--Game.RESET_TO_HERE()
		DisableAllCameras()
		Game.SetHUDIcon("w_dmv")
		Game.SetStageMessageIndex(1)
		Game.SetStageCharacterModel("apu")
		Game.AddStageVehicle("kwik_v", "bm_kwik_dmv", "NULL", "Missions/level01/kwik_vBM.con")
		--Game.AddStageCharacter("bart", "", "", "current", "bm_carstart")
		Game.AddObjective("goto")
			Game.AddNPC("apu", "bm_hide_npc")
			Game.SetDestination("bm_dmv", "upwardglow")
		Game.CloseObjective()
		SetTimeByDifficulty(30, 25)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage(1)
		DisableAllCameras()
		Game.ResetStageHitAndRun()
		Game.SetStageCharacterModel("apu")
		Game.AddStageCharacter("bart", "bm_apu_dmv", "", "current", "bm_car_dmv")
		Game.AddObjective("timer")
			Game.SetDurationTime(1)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage("locked", "car", "")
		DisableAllCameras()
		Game.SetStageMessageIndex(9)
		Game.SetStageCharacterModel("apu")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage(1)
		DisableAllCameras()
		Game.SetStageCharacterModel("apu")
		Game.AddObjective("timer")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage(1)
		DisableAllCameras()
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointResetPlayerInCar("bm_car_dmv2")	--for once, the damn game doesn't spawn me outside the car.
		Game.SetCheckpointDynaLoadData("l5r2.p3d;l5z3.p3d;l5r3.p3d;")
		Game.SetHUDIcon("w_bmitem")
		Game.SetStageMessageIndex(3)
		Game.SetStageCharacterModel("apu")
		SetTrafficByDifficulty(3, 5)
		Game.AddStageCharacter("bart", "", "", "current", "bm_car_dmv2")
		Game.AddObjective("delivery")
			local itemList = {"kwikedog", "squishee", "kwikmag", "butterfinger"}
			local x = 1
			for i = 1, 24 do
				Game.AddCollectible("bm_item" .. i, itemList[x])
				if x >= #itemList then
					x = 1
				else
					x = x + 1
				end
			end
		Game.CloseObjective()
		SetTimeByDifficulty(75, 60)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage(1)
		DisableAllCameras()
		Game.SetHUDIcon("w_kburg")
		Game.SetStageMessageIndex(4)
		Game.SetStageCharacterModel("apu")
		Game.AddStageVehicle("f40", "bm_rival", "NULL", "Missions/level01/BMrival.con", "busm1")
		Game.AddStageVehicle("f40sr2", "bm_rival_goon1", "NULL", "Missions/level01/BMgoon.con", "busm2")
		Game.AddStageVehicle("spyder", "bm_rival_goon2", "NULL", "Missions/level01/BMgoon.con", "male6")
		Game.AddObjective("goto")
			Game.SetDestination("bm_krustyburger", "upwardglow")
		Game.CloseObjective()
		Game.AddStageTime(19)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.ShowStageComplete()
	Game.CloseStage()
	
	Game.AddStage(1)
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointResetPlayerInCar("bm_restart1_forreal")
		Game.SetCheckpointDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
		DisableAllCameras()
		Game.SetHUDIcon("w_f40")
		Game.SetStageMessageIndex(5)
		SetTrafficByDifficulty(2, 3)
		Game.SetStageCharacterModel("apu")
		Game.ActivateVehicle("f40", "NULL", "target")
		Game.ActivateVehicle("f40sr2", "NULL", "chase")
		Game.ActivateVehicle("spyder", "NULL", "chase")
		Game.SetVehicleAIParams("f40", 50, 51)
		Game.SetVehicleAIParams("f40sr2", 50, 51)
		Game.SetVehicleAIParams("spyder", 50, 51)
		for i = 1, 9 do
			Game.AddStageWaypoint("bm_rival_nav" .. i)
		end
		Game.AddObjective("dump")
			local itemList = {"squishee", "butterfinger", "kwikedog", "kwikmag"}
			local x = 1
			for i = 1, 10 do
				Game.AddCollectible("bm_item" .. i, itemList[x])
				if x >= #itemList then
					x = 1
				else
					x = x + 1
				end
			end
			Game.SetObjTargetVehicle("f40")
		Game.CloseObjective()
		Game.SetStageTime(120)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage(1)
		DisableAllCameras()
		Game.SetHUDIcon("w_dmv")
		Game.SetStageMessageIndex(10)
		Game.SetStageCharacterModel("apu")
		SetTrafficByDifficulty(3, 5)
		Game.AddObjective("goto")
			Game.SetDestination("bm_dmv", "upwardglow")
		Game.CloseObjective()
		Game.AddStageTime(34)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.ShowStageComplete()
	Game.CloseStage()
	
	Game.AddStage(0)
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointResetPlayerOutCar("bm_restart1", "bm_car_restart1")
		Game.SetCheckpointDynaLoadData("l5r2.p3d;l5z3.p3d;l5r3.p3d;")
		DisableAllCameras()
		Game.SetHUDIcon("w_kwik")
		Game.SetStageMessageIndex(6)
		Game.SetStageCharacterModel("apu")
		Game.AddStageVehicle("kwik_v", "bm_kwik_dmv", "NULL", "Missions/level01/kwik_vBM.con")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("bm_kwik_enter", "carsphere")
			Game.MustActionTrigger()
		Game.CloseObjective()
		-- then again, every cutscene can be ruined only if the player tried to.
		--[[
		Game.SetStageTime(25)	--prevent player from ruining ending cutscene
		Game.IfCurrentCheckpoint()
			Game.SetStageTime(20)
		Game.EndIf()
		Game.AddCondition("timeout")
		Game.CloseCondition()
		]]
		Game.SetFadeOut(2)
	Game.CloseStage()

	Game.AddStage(0)
		DisableAllCameras()
		Game.ResetStageHitAndRun()
		Game.SetStageAllowMissionCancel(0)
		Game.SetStageCharacterModel("apu")
		Game.AddStageVehicle("kwik_v", "bm_kwik_dmv", "NULL", "Missions/level01/kwik_vBM.con")
		Game.AddStageCharacter("bart", "", "", "current", "bm_hide_car")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
			Game.StayInBlack()
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		DisableAllCameras()
		LockPlayer(9)
		Game.SetStageAllowMissionCancel(0)
		Game.SetStageCharacterModel("apu")
		Game.AddStageCharacter("bart", "", "", "kwik_v", "bm_kwik_dmv")
		Game.AddObjective("timer")
			Game.SetDurationTime(2)
			Game.StayInBlack()
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage(0)
		DisableAllCameras()
		LockPlayer(0)
		Game.DisableHitAndRun()
		Game.SetHUDIcon("w_wash")
		Game.SetStageMessageIndex(7)
		Game.SetMaxTraffic(2)
		Game.SetStageCharacterModel("apu")
		Game.AddStageCharacter("bart", "", "", "kwik_v", "bm_kwik_dmv")
		Game.AddStageVehicle("f40sr2", "bm_ambush_goon1", "NULL", "Missions/level01/BMgoon.con", "busm2")
		Game.AddStageVehicle("spyder", "bm_ambush_goon2", "NULL", "Missions/level01/BMgoon.con", "male6")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("bm_fight_start", "upwardglow")
			Game.SetCollectibleEffect("none")
		Game.CloseObjective()
		SetTimeByDifficulty(39, 34)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditionsInstant()
	Game.CloseStage()
	
	Game.AddStage(0)
		DisableAllCameras()
		Game.DisableHitAndRun()
		Game.SetHUDIcon("w_bmgoons")
		Game.SetStageMessageIndex(8)
		Game.SetStageCharacterModel("apu")
		Game.ActivateVehicle("f40sr2", "NULL", "chase")
		Game.ActivateVehicle("spyder", "NULL", "chase")
		Game.SetVehicleAIParams("f40sr2", 50, 51)
		Game.SetVehicleAIParams("spyder", 50, 51)
		Game.AddObjective("destroycars")
			Game.AddObjTargetModel("f40sr2")
			Game.AddObjTargetModel("spyder")
			Game.SetObjTotal(2)
		Game.CloseObjective()
		Game.SetStageTime(90)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditionsInstant()
	Game.CloseStage()
	
	Game.AddStage(0)
		DisableAllCameras()
		Game.EnableHitAndRun()
		Game.SetHUDIcon("w_wash")
		Game.SetStageMessageIndex(7)
		Game.SetStageCharacterModel("apu")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("bm_carwash", "upwardglow")
		Game.CloseObjective()
		Game.AddStageTime(19)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditionsInstant()
		Game.SetFadeOut(2)
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(1)
		Game.ResetStageHitAndRun()
		Game.SetStageAllowMissionCancel(0)
		--use bart model now
		LockPlayer(9)
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "bm_player_cam1", "", "current", "bm_hide_car")
		Game.AddStageVehicle("kwik_v", "bm_kwik_end", "NULL", "Missions/level01/kwik_vBM.con")
		Game.AddObjective("timer")
			Game.AddDriver("apu", "kwik_v")
			--Game.AddNPC("apu", "bm_apu_npc_end")
			Game.SetDurationTime(1)
			Game.StayInBlack()
		Game.CloseObjective()
		Game.SetMusicState("Mission7", "Silent")
		Game.StageStartMusicEvent("Bonus_start")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(1)
		Game.SetStageAllowMissionCancel(0)
		--use bart model now
		LockPlayer(9)
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "bm_player_cam1", "", "current", "bm_hide_car")
		Game.AddStageVehicle("kwik_v", "bm_kwik_end", "NULL", "Missions/level01/kwik_vBM.con")
		Game.AddObjective("timer")
			Game.AddNPC("bart2", "bm_bart_end")
			Game.SetDurationTime(3)
		Game.CloseObjective()
		Game.StageStartMusicEvent("Bonus_start")
		Game.SetStageMusicAlwaysOn()
		Game.SetCompletionDialog("rivalagain")
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(2)
		Game.SetStageAllowMissionCancel(0)
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "bm_player_cam2", "", "current", "bm_hide_car")
		Game.AddStageVehicle("f40", "bm_rival_cutscene", "evade", "Missions/level01/BMrival.con", "busm1")
		Game.AddStageVehicle("kwik_v", "bm_kwik_end", "NULL", "Missions/level01/kwik_vBM.con")
		Game.SetVehicleAIParams("f40", 50, 51)
		Game.AddStageWaypoint("bm_cutscene_nav1-1")
		Game.AddObjective("timer")
			Game.AddNPC("bart2", "bm_bart_end")
			if Mode.IsNormal then
				Game.SetDurationTime(4.5)
			else 
				Game.SetDurationTime(4)
			end
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_start")
		Game.SetCompletionDialog("oneminute")
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(3)
		Game.SetStageAllowMissionCancel(0)
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "bm_player_cam3", "", "current", "bm_hide_car")
		--Game.AddStageVehicle("f40", "bm_rival", "NULL", "Missions/level01/BMrival.con", "busm1")
		Game.AddStageVehicle("kwik_v", "bm_kwik_end", "evade", "Missions/level01/kwik_vBM.con")
		Game.AddStageWaypoint("bm_cutscene_nav2-1")
		Game.AddObjective("timer")
			Game.RemoveDriver("busm1")
			Game.AddNPC("bart2", "bm_bart_end2")
			Game.SetDurationTime(3.5)
		Game.CloseObjective()
		Game.SetCompletionDialog("rivalhitbyc")
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(3)
		Game.SetStageAllowMissionCancel(0)
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "bm_player_cam3", "", "current", "bm_hide_car")
		Game.AddStageVehicle("f40", "bm_return_cutscene", "NULL", "Missions/level01/BMrival.con", "apu")
		Game.AddObjective("timer")
			Game.RemoveDriver("apu")
			Game.AddDriver("apu", "f40")
			Game.AddNPC("bart2", "bm_bart_end2")
			Game.SetDurationTime(1)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(3)
		Game.SetStageAllowMissionCancel(0)
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "bm_player_cam3", "", "current", "bm_hide_car")
		Game.ActivateVehicle("f40", "NULL", "evade")
		Game.AddStageWaypoint("bm_cutscene_nav1-1")
		Game.AddObjective("timer")
			Game.AddNPC("bart2", "bm_bart_end2")
			if Mode.IsNormal then
				Game.SetDurationTime(3.0)
			else 
				Game.SetDurationTime(2.5)
			end
		Game.CloseObjective()
		Game.SetFadeOut(2)
	Game.CloseStage()
	
	Game.AddStage(0)
		DisableAllCameras()
		Game.SetMaxTraffic(5)
		Game.AddStageCharacter("bart", "bm_bart_end3", "", "current", "bm_hide_car")
		Game.AddStageVehicle("f40", "bm_kwik_end2", "NULL", "Missions/level01/BMrival.con")
		Game.AddObjective("timer")
			Game.RemoveDriver("apu")
			Game.AddNPC("bart2", "bm_hide_npc")
			Game.AddNPC("apu", "bm_apu_npc_end")
			--Game.AddObjectiveNPCWaypoint("apu", "bm_apu_npc_walk")
			Game.SetDurationTime(3)
		Game.CloseObjective()
		Game.SetCompletionDialog("coolcar")
	Game.CloseStage()
	
	--why the fuck does the completion dialog play twice?
	Game.AddStage(0, "final")
		DisableAllCameras()
		Game.AddStageVehicle("f40", "bm_kwik_end2", "NULL", "Missions/level01/BMrival.con")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
	Game.CloseStage()
Game.CloseMission()