Game.SelectMission("m0")

	Game.SetMissionResetPlayerInCar("m0_carstart_2")
	Game.SetDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
	Game.StreetRacePropsLoad("l1m1_baracade.p3d;") -- Barracade
	--Game.StreetRacePropsUnload("l1m1_baracade.p3d:") -- Barracade
	Game.SetNumValidFailureHints( Mode.FailHintCount )

	Game.SetPedsEnabled(1)

	Game.UsePedGroup(5)

	Game.AddStage()
		Game.SetStageMessageIndex(02)
		Game.AddObjective("getin")
			Game.AddNPC("npd","hidden_npc")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.RESET_TO_HERE()
		Game.SetStageMessageIndex(07)
		Game.SetHUDIcon("w_kburg")
		SetTrafficByDifficulty(2, 4)
		Game.AddObjective("goto")
			Game.SetDestination("m0_kburger1","upwardglow")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		SetTimeByDifficulty(30, 20)
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()

	Game.AddStage()
		Game.SetHUDIcon("w_teen")
		Game.SetStageMessageIndex(08)
		Game.AddObjective("goto")
			Game.SetDestination("m0_order_loc","triggersphere")
			Game.MustActionTrigger()
			Game.SetCollectibleEffect("none")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.AddObjective("dialogue")
			Game.AddNPC("npd","m0_npd")
			Game.AmbientAnimationRandomize( 1, 0 )
			Game.AmbientAnimationRandomize( 0, 0 )
			Game.SetConversationCam( 0, "npc_near" )
			Game.SetConversationCam( 1, "npc_near" )
			Game.SetConversationCam( 2, "npc_near" )
			Game.SetConversationCam( 3, "npc_near" )
			Game.SetConversationCam( 4, "npc_near" )
			Game.SetConversationCam( 5, "npc_near" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientPcAnimation( "dialogue_shake_hand_in_air" )
			Game.AddAmbientPcAnimation( "none" )
			Game.AddAmbientPcAnimation( "dialogue_yes" )
			Game.AddAmbientPcAnimation( "none" )
			Game.AddAmbientPcAnimation( "dialogue_hands_in_air" )
			Game.SetDialogueInfo("bart","npd","order",0)
			Game.SetDialoguePositions("m0_bart_kbcam","m0_npd","m0_kburg_car")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.SetStageMessageIndex(03)
		Game.SetHUDIcon("w_kbmeal")
		--[[
		Game.AddObjective("goto")
			Game.SetDestination("m0_kburger2","kmeal")
		Game.CloseObjective()
		]]
		Game.AddObjective("delivery", "neither")
			Game.RemoveNPC("npd")
			for i=1, 4 do
			Game.AddCollectible("m0_kmeal" .. i,"kmeal")
			end
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.SetStageMessageIndex(02)
		Game.AddObjective("getin")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
		SetTimeByDifficulty(60, 45)
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.SetStageMessageIndex(05)
		Game.SetHUDIcon("w_save")
		Game.AddObjective("goto")
			Game.SetDestination("m0_trynsave","upwardglow")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddStageTime(-1)
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetStageMessageIndex(6)
		Game.SetHUDIcon( "w_m0item" )
		Game.AddObjective("delivery", "neither")
			local items = {"firewrks", "cd", "blankbox"}
			local x = 1
			for i= 1,14 do
				Game.AddCollectible("m0_fire"..i, items[x])
				x = x + 1
				if x > #items then
					x = 1
				end
			end
			Game.SetCollectibleEffect("wrench_collect")
		Game.CloseObjective()
		SetTimeByDifficulty(45, 35)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
	Game.CloseStage()
	
	
	Game.AddStage()
		Game.SetHUDIcon("w_fone")
		Game.SetStageMessageIndex(13)
		Game.AddObjective("goto")
			Game.SetDestination("m0_phone_veterans","triggersphere")
			Game.MustActionTrigger()
			Game.SetCollectibleEffect("none")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.AddObjective("dialogue")
			Game.AddNPC("npd","m0_npd_phone_veterans")
			Game.AmbientAnimationRandomize( 1, 0 )
			Game.AmbientAnimationRandomize( 0, 0 )
			Game.SetConversationCam( 0, "npc_far" )
			Game.SetConversationCam( 1, "npc_far" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientPcAnimation( "none" )
			Game.AddAmbientPcAnimation( "dialogue_yes" )
			Game.SetDialogueInfo("bart","npd","phone2",0)
			Game.SetDialoguePositions("m0_bart_phone_veterans","m0_npd_phone_veterans","m0_car_phone_veterans")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.SetHUDIcon("w_mono")
		Game.SetStageMessageIndex(11)
		Game.SetMaxTraffic(2)
		Game.AddObjective("goto")
			Game.RemoveNPC("npd")
			Game.AddNPC("snake", "m1_snake_sd")
			Game.SetDestination("m0_fakeloc","upwardglow")
			Game.AddStageVehicle("homer_v","m0_homer","NULL","Missions\\level01\\M0chase.con", "homer")
			Game.AddStageVehicle("snake_v","m0_snake_car","NULL","Missions/level01/M1dest.con")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		SetTimeByDifficulty(60, 45)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetCompletionDialog("dad","homer")
	Game.CloseStage()

	Game.AddStage()
		Game.ShowStageComplete()
		Game.SetHUDIcon( "w_homcar" )
		Game.SetStageMessageIndex(10)
		Game.AddStageTime(30)
		Game.ActivateVehicle("homer_v","NULL","chase")
		Game.AddObjective("losetail")
			Game.AddNPC("snake", "m1_snake_sd")
			Game.SetObjTargetVehicle("homer_v")
			Game.SetObjDistance(150)
		Game.CloseObjective()
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.SetCompletionDialog("dad2","homer")
	Game.CloseStage()

	Game.AddStage()
		Game.SetStageMessageIndex(12)
		Game.SetHUDIcon("w_mono")
		Game.AddStageVehicle("snake_v","m0_snake_car","NULL","Missions/level01/M1dest.con")
		Game.AddObjective("goto")
			Game.AddNPC("snake", "m1_snake_sd")
			Game.SetDestination("m0_final_loc","upwardglow")
		Game.CloseObjective()
		Game.AddStageTime(30)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
	Game.CloseStage()
	
	-- so player doesn't lose control after reaching destination
	-- turning goto stage into race works too, but that will crash game if an AI is set to chase or NULL
	Game.AddStage("final")
		Game.AddStageVehicle("snake_v","m0_snake_car","NULL","Missions/level01/M1dest.con")
		Game.AddObjective("timer")
			Game.AddNPC("snake", "m1_snake_sd")
			Game.SetDurationTime(0)
		Game.CloseObjective()
	Game.CloseStage()

--	Game.AddStage()
--		Game.SetHUDIcon("w_fone")
--		Game.SetStageMessageIndex(04)
--		Game.AddObjective("goto")
--			Game.AddNPC("npd","m0_npd_cam")
--			Game.SetDestination("m0_phone_loc","triggersphere")
--			Game.MustActionTrigger()
--			Game.SetCollectibleEffect("none")
--		Game.CloseObjective()

--	Game.CloseStage()

--	Game.AddStage("final")
--		Game.AddObjective("dialogue")
--			Game.AddNPC("npd","m0_npd_2")
--			Game.AmbientAnimationRandomize( 1, 0 )
--			Game.AmbientAnimationRandomize( 0, 0 )
--			Game.SetConversationCam( 0, "npc_far" )
--			Game.SetConversationCam( 1, "npc_far" )
--			Game.AddAmbientNpcAnimation( "dialogue_open_arm_hand_gesture" )
--			Game.AddAmbientNpcAnimation( "none" )
--			Game.AddAmbientNpcAnimation( "dialogue_thinking" )
--			Game.AddAmbientPcAnimation( "none" )
--			Game.AddAmbientPcAnimation( "dialogue_scratch_head" )
--			Game.AddAmbientPcAnimation( "none" )
--			Game.AddAmbientPcAnimation( "dialogue_hands_in_air" )
--			Game.SetDialogueInfo("bart","npd","phone2",0)
--		Game.CloseObjective()
--	Game.CloseStage()

Game.CloseMission()