Game.SelectMission("m0")

	Game.SetMissionResetPlayerInCar("m0_carstart_2")
	Game.SetDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
	Game.StreetRacePropsLoad("l1m1_baracade.p3d;") -- Barracade
	Game.StreetRacePropsUnload("l1m1_baracade.p3d:") -- Barracade

	Game.UsePedGroup(5)

	if Mode.IsNormal then
	Game.AddStage()
		Game.SetStageMessageIndex(02)
		Game.AddObjective("getin")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
	Game.CloseStage()
	end

	Game.AddStage()
		Game.RESET_TO_HERE()
		Game.SetStageMessageIndex(07)
		Game.SetHUDIcon("w_kburg")
		Game.AddObjective("goto")
			Game.SetDestination("m0_kburger1","carsphere")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		if Mode.IsNormal then
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		end
		Game.SetStageTime(30)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage()
		Game.SetHUDIcon("w_teen")
		Game.SetStageMessageIndex(08)
		Game.AddObjective("goto")
			Game.AddNPC("npd","m0_npd")
			Game.SetDestination("m0_order_loc","triggersphere")
			Game.MustActionTrigger()
			Game.SetCollectibleEffect("none")
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage()
		Game.AddObjective("dialogue")
			Game.AddNPC("npd","m0_npd")
			Game.AmbientAnimationRandomize( 1, 0 )
			Game.AmbientAnimationRandomize( 0, 0 )
			Game.SetConversationCam( 0, "npc_near" )
			Game.SetConversationCam( 1, "npc_near" )
			Game.SetConversationCam( 2, "npc_near" )
			Game.SetConversationCam( 3, "npc_near" )
			Game.SetConversationCam( 4, "npc_near" )
			Game.SetConversationCam( 5, "npc_near" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientPcAnimation( "none" )
			Game.AddAmbientPcAnimation( "dialogue_scratch_head" )
			Game.AddAmbientPcAnimation( "none" )
			Game.SetDialogueInfo("bart","npd","order",0)
			Game.SetDialoguePositions("m0_bart_kbcam","m0_npd","m0_kburg_car")
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage()
		Game.SetStageMessageIndex(03)
		Game.SetHUDIcon("w_kbmeal")
		Game.AddObjective("goto")
			Game.SetDestination("m0_kburger2","kmeal")
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	if Mode.IsNormal then
	Game.AddStage()
		Game.SetStageMessageIndex(02)
		Game.AddObjective("getin")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	end
	
	Game.AddStage()
		Game.SetStageMessageIndex(05)
		Game.SetHUDIcon("w_save")
		Game.AddObjective("goto")
			Game.SetDestination("m0_trynsave","carsphere")
		Game.CloseObjective()
		if Mode.IsNormal then
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		end
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddStageTime(45)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetStageMessageIndex(6)
		Game.SetHUDIcon( "w_fire" )
		Game.AddObjective("delivery", "neither")
		for i= 1,11 do
			Game.AddCollectible("m0_fire"..i,"firewrks"); 
		end
			Game.SetCollectibleEffect("wrench_collect")
		Game.CloseObjective()
		if Mode.IsNormal then
		Game.SetStageTime(35)
		else
		Game.SetStageTime(25)
		end
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
		Game.ShowStageComplete()
	Game.CloseStage()

	Game.AddStage()
		Game.SetHUDIcon("w_fone")
		Game.SetStageMessageIndex(01)
		Game.AddObjective("goto")
			Game.SetDestination("m0_fakeloc","carsphere")
			Game.AddStageVehicle("homer_v","m0_homer","NULL","Missions\\level01\\M0chase.con", "homer")
		Game.CloseObjective()
		Game.AddCondition("outofvehicle")
		Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		if Mode.IsHard  then
		Game.SetStageTime(45)
		else
		Game.SetStageTime(60)
		end
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetCompletionDialog("dad","homer")
	Game.CloseStage()

	Game.AddStage()
		Game.ShowStageComplete()
		Game.SetHUDIcon( "w_homcar" )
		Game.SetStageMessageIndex(10)
		if Mode.IsNormal then
		Game.AddStageTime(-1)
		else
		Game.AddStageTime(10)
		end
		Game.ActivateVehicle("homer_v","NULL","chase")
		Game.AddObjective("losetail")
			Game.SetObjTargetVehicle("homer_v")
			if Mode.IsNormal then
			Game.SetObjDistance(135)
			else
			Game.SetObjDistance(150)
			end
		Game.CloseObjective()
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.SetCompletionDialog("dad2","homer")
	Game.CloseStage()

	Game.AddStage("final")
		Game.SetStageMessageIndex(1)
		Game.SetHUDIcon("w_fone")
		Game.AddObjective("goto")
			Game.SetDestination("m0_final_loc","carsphere")
		Game.CloseObjective()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
	Game.CloseStage()

--	Game.AddStage()
--		Game.SetHUDIcon("w_fone")
--		Game.SetStageMessageIndex(04)
--		Game.AddObjective("goto")
--			Game.AddNPC("npd","m0_npd_cam")
--			Game.SetDestination("m0_phone_loc","triggersphere")
--			Game.MustActionTrigger()
--			Game.SetCollectibleEffect("none")
--		Game.CloseObjective()
--		Game.SetStageMusicAlwaysOn()
--	Game.CloseStage()

--	Game.AddStage("final")
--		Game.AddObjective("dialogue")
--			Game.AddNPC("npd","m0_npd_2")
--			Game.AmbientAnimationRandomize( 1, 0 )
--			Game.AmbientAnimationRandomize( 0, 0 )
--			Game.SetConversationCam( 0, "npc_far" )
--			Game.SetConversationCam( 1, "npc_far" )
--			Game.AddAmbientNpcAnimation( "dialogue_open_arm_hand_gesture" )
--			Game.AddAmbientNpcAnimation( "none" )
--			Game.AddAmbientNpcAnimation( "dialogue_thinking" )
--			Game.AddAmbientPcAnimation( "none" )
--			Game.AddAmbientPcAnimation( "dialogue_scratch_head" )
--			Game.AddAmbientPcAnimation( "none" )
--			Game.AddAmbientPcAnimation( "dialogue_hands_in_air" )
--			Game.SetDialogueInfo("bart","npd","phone2",0)
--		Game.CloseObjective()
--	Game.CloseStage()

Game.CloseMission()