Game.SelectMission("m1")

Game.SetMissionResetPlayerInCar("m1_car_loc")
Game.SetDynaLoadData("l5z4.p3d;l5r3.p3d;l5r4.p3d;")
Game.StreetRacePropsLoad("l1m1_baracade.p3d;") -- Barracade
Game.StreetRacePropsUnload("l1m1_baracade.p3d:") -- Barracade

Game.UsePedGroup(5)

Game.AddStage()
Game.RESET_TO_HERE()
Game.SetStageMessageIndex(4)
Game.SetHUDIcon( "w_snakec" )
Game.AddStageVehicle("snake_v","m1_snk_car","target","Missions\\level01\\M1dest.con", "snake")
Game.SetVehicleAIParams( "snake_v", -10, -9 )
Game.AddStageWaypoint( "m1_dmv_fail" )
Game.AddStageCharacter("bart", "", "", "current", "m1_car_loc")
Game.AddObjective("destroy")
Game.SetObjTargetVehicle("snake_v")
Game.SetFadeOut(0.1)
Game.CloseObjective()
Game.AddCondition("race")
Game.SetCondTargetVehicle("snake_v")
Game.CloseCondition()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
Game.AddCondition("followdistance")
Game.SetFollowDistances(0, 100)
Game.SetCondTargetVehicle("snake_v")
Game.CloseStage()

Game.AddStage()
Game.AddObjective("timer")
Game.SetStageAllowMissionCancel(0)
Game.StayInBlack()
Game.SetDurationTime(0.1)
Game.AddStageCharacter("bart", "spawn_player_to_cam_here", "", "current", "m1_car_loc")
Game.CloseObjective()
Game.StageStartMusicEvent("M3_drama")
Game.SetStageMusicAlwaysOn()
Game.CloseStage()

Game.AddStage(0) -- AAAAAAAAAAA CINEMATICS
Game.CHECKPOINT_HERE()
Game.SetCheckpointDynaLoadData("l5z3.p3d;l5r2.p3d;l5r3.p3d;")
Game.SetCheckpointResetPlayerOutCar("spawn_player_to_cam_here" , "m1_car_loc" )
Game.SetStageAllowMissionCancel(0)
Game.SetStageMessageIndex(6)
Game.SetMaxTraffic(0)
Game.AddStageCharacter("bart", "spawn_player_to_cam_here", "", "current", "m1_car_loc")
Game.AddStageWaypoint("m1_wp_1")
Game.AddStageWaypoint("m1_wp_2")
Game.AddStageWaypoint("m1_wp_3")
Game.AddObjective("timer")
Game.AddStageVehicle("cPolic2","m1_pig1","evade","Missions\\level04\\M7Evade.con")
Game.AddStageVehicle("cPolic3","m1_pig2","evade","Missions\\level04\\M7Evade.con","wiggum")
Game.SetDurationTime(7.5)
Game.SetFadeOut(0.1)
Game.CloseObjective()
Game.StageStartMusicEvent("M3_drama")
Game.SetStageMusicAlwaysOn()
Game.CloseStage()

Game.AddStage()
Game.DisableTrigger("some_camera_locator")
Game.SetMaxTraffic(4)
Game.AddObjective("timer")
Game.SetDurationTime(1)
--Game.AddStageCharacter("bart", "", "", "current", "m1_car_loc")
-- It really wouldn't make sense that you're sneaking out of the park if your car is right next to ya
-- Immersion in SHAR modding is kinda taboo lmao
Game.StayInBlack()
Game.CloseObjective()
Game.SetStageMusicAlwaysOn()
Game.CloseStage()

Game.AddStage()
Game.DisableTrigger("some_camera_locator") -- THIS LINE IS NEEDED FOR EVERY STAGE AFTER "AAAAAAAAAAA CINEMATICS"
Game.SetHUDIcon("w_police")
Game.SetStageMessageIndex(7)
Game.AddObjective("hitandrunlost")
Game.AddStageCharacter("bart", "", "", "current", "m1_checkpoint")
Game.CloseObjective()
Game.SetNoHitAndRunMusicForStage()
Game.AddCondition("hitandruncaught")
Game.SetCondDelay( 2 )
Game.CloseCondition()
Game.SetStageHitAndRunFine(0)
Game.SetStageHitAndRun(100)
if Mode.IsHard then
Game.SetHitAndRunDecayHitAndRun(4.5)
else
Game.SetHitAndRunDecayHitAndRun(5.0)
end
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.ShowStageComplete()
Game.CloseStage()

Game.AddStage()
Game.DisableTrigger("some_camera_locator")
Game.SetStageMessageIndex(08)
Game.SetHUDIcon("w_dmv")
Game.AddObjective("goto")
Game.SetDestination("m1_dmv","carsphere")
Game.AddNPC("wiggum", "m1_officer_loc")
Game.AddStageVehicle("cPolic3","m1_police_loc","NULL","Missions\\level01\\M0chase.con")
Game.CloseObjective()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
Game.StageStartMusicEvent("M1_start")
Game.CloseStage()

Game.AddStage(0)
Game.DisableTrigger("some_camera_locator")
Game.SetStageMessageIndex(12)
Game.SetHUDIcon("w_wig")
Game.AddObjective("talkto")
Game.AddNPC("wiggum", "m1_officer_loc")
Game.SetTalkToTarget("wiggum", 0, 0)
Game.CloseObjective()
Game.CloseStage()

Game.AddStage()
Game.DisableTrigger("some_camera_locator")
Game.AddObjective("dialogue")
Game.AddNPC("wiggum","m1_officer_loc")
Game.AmbientAnimationRandomize( 1, 0 )
Game.AmbientAnimationRandomize( 0, 0 )
Game.SetConversationCam( 0, "npc_near" )
Game.SetConversationCam( 1, "pc_near" )
Game.AddAmbientNpcAnimation( "none" )
Game.AddAmbientNpcAnimation( "none" )
Game.AddAmbientNpcAnimation( "none" )
Game.AddAmbientPcAnimation( "none" )
Game.AddAmbientPcAnimation( "dialogue_scratch_head" )
Game.AddAmbientPcAnimation( "none" )
Game.SetDialogueInfo("bart","wiggum","crime",0)
Game.CloseObjective()
Game.CloseStage()

Game.AddStage("final")
Game.DisableTrigger("some_camera_locator")
Game.SetStageMessageIndex(10)
Game.SetHUDIcon( "w_fire" )
Game.AddObjective("delivery", "neither")
Game.AddCollectible("m1_fire_1","i_firewk")
Game.AddCollectible("m1_fire_2","kmeal")
Game.AddCollectible("m1_fire_3","kmeal")
Game.CloseObjective()
Game.CloseStage()

Game.CloseMission()