Game.SelectMission("m1")

Game.SetMissionResetPlayerInCar("m1_car_loc")
Game.SetDynaLoadData("l5z4.p3d;l5r3.p3d;l5r4.p3d;")
Game.StreetRacePropsLoad("l1m1_baracade.p3d;") -- Barracade
Game.StreetRacePropsUnload("l1m1_baracade.p3d:") -- Barracade

Game.UsePedGroup(5)
Game.SetNumValidFailureHints( 5 )

Game.AddStage()
Game.RESET_TO_HERE()
Game.SetStageMessageIndex(4)
Game.SetMaxTraffic(2)
Game.SetHUDIcon( "w_snakec" )
Game.PlacePlayerCar("current", "m1_car_loc")
Game.PutMFPlayerInCar( )
Game.AddStageVehicle("snake_v","m1_snk_car","target","Missions\\level01\\M1dest.con", "snake")
Game.SetVehicleAIParams( "snake_v", -10, -9 )
Game.AddStageWaypoint( "m1_dmv_fail" )
--Game.AddStageCharacter("bart", "", "", "current", "m1_car_loc")
Game.AddObjective("destroy")
Game.SetObjTargetVehicle("snake_v")
Game.AddNPC("snake","m0_npd_sd")
Game.CloseObjective()
Game.AddCondition("race")
Game.SetCondTargetVehicle("snake_v")
Game.CloseCondition()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
Game.SetFadeOut(0.1)
if Mode.IsHard then
Game.AddCondition("followdistance")
Game.SetFollowDistances(0, 100)
Game.SetCondTargetVehicle("snake_v")
end
Game.CloseStage()

Game.AddStage()
Game.SetHUDIcon("w_police")
Game.SetStageMessageIndex(05)
Game.AddObjective("timer")
Game.SetDurationTime(1)
Game.CloseObjective()
Game.SetStageHitAndRunFine(0)
Game.SetStageHitAndRun(75)
Game.SetStageMusicAlwaysOn()
Game.CloseStage()

Game.AddStage()
Game.CHECKPOINT_HERE()
Game.SetCheckpointDynaLoadData("l5z3.p3d;l5r2.p3d;l5r3.p3d;")
Game.SetCheckpointResetPlayerInCar("m1_checkpoint")
Game.SetHUDIcon("w_police")
Game.SetStageMessageIndex(7)
Game.AddObjective("hitandrunlost")
Game.CloseObjective()
Game.SetNoHitAndRunMusicForStage()
Game.AddCondition("hitandruncaught")
Game.SetCondDelay( 2 )
Game.CloseCondition()
Game.SetStageHitAndRunFine(0)
Game.SetStageHitAndRun(100)
Game.SetHitAndRunDecayHitAndRun(5.0)
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.ShowStageComplete()
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(08)
Game.SetHUDIcon("w_dmv")
Game.AddObjective("goto")
Game.SetDestination("m1_dmv","carsphere")
Game.AddNPC("wiggum", "m1_officer_loc")
Game.AddStageVehicle("cPolic2","m1_police_loc","NULL","Missions\\level01\\M0chase.con")
Game.CloseObjective()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
Game.StageStartMusicEvent("M1_start")
Game.CloseStage()

Game.AddStage(0)
Game.SetStageMessageIndex(12)
Game.SetHUDIcon("w_wig")
Game.AddObjective("talkto")
Game.AddNPC("wiggum", "m1_officer_loc")
Game.SetTalkToTarget("wiggum", 0, 0)
Game.CloseObjective()
Game.CloseStage()

Game.AddStage()
Game.AddObjective("dialogue")
Game.AddNPC("wiggum","m1_officer_loc")
Game.AmbientAnimationRandomize( 1, 0 )
Game.AmbientAnimationRandomize( 0, 0 )
Game.SetConversationCam( 0, "npc_near" )
Game.SetConversationCam( 1, "pc_near" )
Game.SetConversationCam( 2, "npc_near" )
Game.SetConversationCam( 3, "pc_near" )
Game.SetConversationCam( 4, "npc_near" )
Game.AddAmbientNpcAnimation( "none" )
Game.AddAmbientNpcAnimation( "none" )
Game.AddAmbientNpcAnimation( "none" )
Game.AddAmbientPcAnimation( "none" )
Game.AddAmbientPcAnimation( "dialogue_scratch_head" )
Game.AddAmbientPcAnimation( "none" )
Game.SetDialogueInfo("bart","wiggum","crime",0)
Game.CloseObjective()
Game.CloseStage()

Game.AddStage("final")
Game.SetStageMessageIndex(10)
Game.SetHUDIcon( "w_fire" )
Game.AddObjective("delivery", "neither")
Game.AddCollectible("m1_fire_1","i_firewk")
Game.AddCollectible("m1_fire_2","kmeal")
Game.AddCollectible("m1_fire_3","kmeal")
Game.CloseObjective()
Game.CloseStage()

Game.CloseMission()