local timeLimit = {60, 60}

local function DisableAllCameras()
	Game.DisableTrigger("some_camera_locator")
	Game.DisableTrigger("m2_camera2")
	Game.DisableTrigger("m2_camera3")
end

Game.SelectMission("m2")

	Game.SetMissionResetPlayerInCar("m2_car_loc")
	--Game.SetDynaLoadData("l5z3.p3d;l5r2.p3d;l5r3.p3d;")
	Game.SetDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
	Game.StreetRacePropsLoad("l1m1_baracade.p3d;")	-- Barracade
	Game.StreetRacePropsUnload("l1m1_baracade.p3d:m2_cops.p3d:")	-- Barracade and Cop Props.
	Game.SetPedsEnabled(1)

	Game.UsePedGroup(5)
	if Mode.IsHard then
	Game.SetNumValidFailureHints( 5 )
	else
	Game.SetNumValidFailureHints( 4 )
	end
	
	Game.AddStage(0)
		DisableAllCameras()
		Game.DisableTrigger("m2_police_loader")
		Game.SetStageMessageIndex(12)
		Game.AddStageVehicle("cLimo","m2_limostart","NULL","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerdrace","NULL","Missions\\level01\\M2nerd.con","male2")
		Game.AddObjective("getin")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		Game.RESET_TO_HERE()
		DisableAllCameras()
		Game.DisableTrigger("m2_police_loader")
		Game.SetStageMessageIndex(3)
		Game.SetMaxTraffic(5)
		Game.SetHUDIcon("w_hotel")
		Game.AddStageVehicle("cLimo","m2_limostart","NULL","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerdrace","NULL","Missions\\level01\\M2nerd.con","male2")
		Game.AddObjective("goto")
			Game.SetDestination("m2_hotel","carsphere")
		Game.CloseObjective()
		timeLimit[Mode.NormalMode] = 30
		timeLimit[Mode.HardMode] = 20
		Game.SetStageTime(timeLimit[Mode.Current])
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage(0)
		DisableAllCameras()
		Game.DisableTrigger("m2_police_loader")
		Game.SetHUDIcon("w_hotel")
		Game.SetStageMessageIndex(8)
		Game.AddStageVehicle("cLimo","m2_limostart","NULL","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerdrace","NULL","Missions\\level01\\M2nerd.con","male2")
		Game.AddObjective("goto")
			--Game.AddNPC("npd","m2_npd2")
			Game.SetDestination("m2_wedding_1","triggersphere")
			Game.MustActionTrigger()
			Game.SetCollectibleEffect("none")
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage(0) -- THOMAS DIALOG AAAAAAAAAAA
		DisableAllCameras()
		Game.DisableTrigger("m2_police_loader")
		Game.NoTrafficForStage()	--there shouldn't be traffic enabled beyond this part because of the police props.
		Game.AddStageVehicle("cLimo","m2_limostart","NULL","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerdrace","NULL","Missions\\level01\\M2nerd.con","male2")
		Game.AddObjective("dialogue")
			Game.AddNPC("npd","m2_npd2")
			Game.AmbientAnimationRandomize( 1, 0 )
			Game.AmbientAnimationRandomize( 0, 0 )
			Game.SetConversationCam( 0, "npc_near" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientPcAnimation( "none" )
			Game.AddAmbientPcAnimation( "dialogue_scratch_head" )
			Game.AddAmbientPcAnimation( "none" )
		Game.SetDialogueInfo("bart","npd","wedding",0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		-- the reason the glass sound effect is bart dialog is because it's easier lol
		-- considering the stage is faded out
		-- Basically if I use a FadeOut command it's because what I wanted to create just isn't feasible in MFK scripts
		-- even with ASF commands
		DisableAllCameras()
		Game.DisableTrigger("m2_police_loader")
		Game.SetStageMessageIndex(4)
		Game.SetHUDIcon("w_limo")
		Game.NoTrafficForStage()
		Game.AddStageVehicle("cLimo","m2_limostart","NULL","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerdrace","NULL","Missions\\level01\\M2nerd.con","male2")
		Game.AddObjective("goto")
			Game.SetDestination("m2_steal","triggersphere")
			Game.RemoveNPC("npd")
			Game.MustActionTrigger()
			Game.SetCollectibleEffect("none")
			Game.SetFadeOut(0.5)
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
		Game.SetCompletionDialog("glass")
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetStageAllowMissionCancel(0)
		Game.NoTrafficForStage()
		DisableAllCameras()
		Game.AddStageVehicle("cLimo","m2_limostart","NULL","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerdrace","NULL","Missions\\level01\\M2nerd.con","male2")
		Game.AddStageCharacter("bart", "", "", "current", "m2_racestart_cops")	--move player to enable cop props.
		Game.AddObjective("timer")
			Game.SetDurationTime(2)
			Game.StayInBlack()
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetStageAllowMissionCancel(0)
		Game.NoTrafficForStage()
		DisableAllCameras()
		Game.AddStageVehicle("cLimo","m2_limostart","NULL","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerdrace","NULL","Missions\\level01\\M2nerd.con","male2")
		Game.AddStageCharacter("bart", "", "", "current", "m2_racestart")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
		Game.ShowStageComplete() -- Checkpoint Notification
	Game.CloseStage()

	Game.AddStage(0)
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointDynaLoadData("l5r1.p3d;l5z2.p3d;l5r2.p3d;m2_cops.p3d;")
		Game.SetCheckpointResetPlayerInCar("m2_racestart" )
		DisableAllCameras()
		Game.SetStageMessageIndex(5)
		Game.SetHUDIcon("w_park")
		Game.DisableHitAndRun()
		Game.NoTrafficForStage()
		Game.ActivateVehicle("cLimo","NULL","chase")
		Game.ActivateVehicle("cNerd","NULL","chase")
		Game.AddStageWaypoint( "m2_raceend" )
		Game.AddObjective( "goto")
			Game.AddNPC("lou","m2_crowd_npc1")
			Game.AddNPC("eddie","m2_crowd_npc2")
			Game.AddNPC("wiggum","m2_crowd_npc3")
			Game.SetDestination("m2_police_interrupt","carsphere")
			Game.SetCollectibleEffect("wrench_collect")
		Game.CloseObjective()
		timeLimit[Mode.NormalMode] = 30
		timeLimit[Mode.HardMode] = 20
		Game.SetStageTime(timeLimit[Mode.Current])
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current")
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

--[[
	Game.AddStage(0) -- AAAAAAAAAAA CINEMATICS
		-- Obligatory checkpoint because players new to this stage have only trial and error to find inside/outside triggers
		Game.SetStageAllowMissionCancel(0)
		Game.SetMaxTraffic(0)
		Game.AddStageCharacter("bart", "spawn_player_to_cam_here", "", "current", "m2_car")
		for i= 1,5 do
		Game.AddStageWaypoint("m2_wp_"..i)
		end
		Game.AddObjective("timer")
			Game.AddStageVehicle("cLimo2","m2_nerdcam","evade","Missions\\level04\\M7Evade.con","mobstr")
			Game.AddStageVehicle("cNerd","m2_limocam","evade","Missions\\level04\\M7Evade.con","male2")
			Game.SetDurationTime(7.5)
			Game.SetFadeOut(0.1)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M2_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
]]

	
	Game.AddStage(0) -- AAAAAAAAAAA CINEMATICS
		-- Obligatory checkpoint because players new to this stage have only trial and error to find inside/outside triggers
		Game.DisableTrigger("m2_camera2")
		Game.DisableTrigger("m2_camera3")
		Game.SetStageAllowMissionCancel(0)
		Game.SetMaxTraffic(0)
		Game.AddStageCharacter("bart", "spawn_player_to_cam_here", "", "current", "m2_racestart")
		Game.AddStageVehicle("cLimo","m2_limo_escape","NULL","Missions\\level01\\M2limo.con","mobstr")	--hide
		Game.AddStageVehicle("cNerd","m2_nerd_escape","NULL","Missions\\level01\\M2nerd.con","male2")	--hide
		Game.AddObjective("timer")
			Game.SetDurationTime(2)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M2_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Output([[
		AddStage("locked", "car", "");
	]]) -- AAAAAAAAAAA CINEMATICS
		-- Obligatory checkpoint because players new to this stage have only trial and error to find inside/outside triggers
		Game.DisableTrigger("m2_camera2")
		Game.DisableTrigger("m2_camera3")
		Game.SetStageAllowMissionCancel(0)
		Game.SetStageMessageIndex(9)
		Game.SetMaxTraffic(0)
		Game.AddStageCharacter("bart", "spawn_player_to_cam_here", "", "current", "m2_racestart")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M2_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	
	Game.AddStage(0)
		Game.DisableTrigger("m2_camera2")
		Game.DisableTrigger("m2_camera3")
		Game.SetStageAllowMissionCancel(0)
		Game.SetMaxTraffic(0)
		Game.AddStageCharacter("bart", "spawn_player_to_cam_here", "", "current", "m2_racestart")
		Game.AddObjective("timer")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.SetIrisWipe(0.1)
		Game.StageStartMusicEvent("M2_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

--[[
	Game.AddStage() -- teleports the player back from the camera to playable stage
		Game.DisableTrigger("some_camera_locator") -- THIS LINE IS NEEDED FOR EVERY STAGE AFTER "AAAAAAAAAAA CINEMATICS"
		Game.SetStageAllowMissionCancel(0)
		Game.AddObjective("timer")
			Game.SetDurationTime(1)
			Game.AddStageCharacter("bart", "m2_bart_escape", "", "current", "m2_car")
		Game.CloseObjective()
		Game.StageStartMusicEvent("M2_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage()
		Game.DisableTrigger("some_camera_locator")
		Game.StartCountdown("count")
		Game.AddToCountdownSequence( "o", 100 )
		Game.AddObjective("timer")
			Game.SetDurationTime(1)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M2_drama")
		Game.ShowStageComplete() -- Checkpoint Notification
	Game.CloseStage()
]]

	Game.AddStage(0)
		DisableAllCameras()
		Game.DisableTrigger("Z1p2")	--phonebooth near m2_escape
		Game.CHECKPOINT_HERE()
		--Game.SetCheckpointDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
		Game.SetCheckpointDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;m2_cops.p3d;")
		Game.SetCheckpointResetPlayerOutCar( "m2_bart_escape", "m2_racestart" )
		Game.AddStageVehicle("cLimo","m2_limo_escape","NULL","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerd_escape","NULL","Missions\\level01\\M2nerd.con","male2")
		Game.AddStageCharacter("bart", "m2_bart_escape", "", "current", "m2_racestart")
		Game.SetHUDIcon("w_fone")
		Game.SetStageMessageIndex(6)
		--Game.SetMaxTraffic(4)
		Game.NoTrafficForStage()
		Game.AddObjective("goto")
			--Game.AddNPC("male2","m2_crowd_npc1")
			--Game.AddNPC("olady2","m2_crowd_npc2")
			--Game.AddNPC("male4","m2_crowd_npc3")
			--Game.AddNPC("fem3","m2_crowd_npc4")
			Game.AddNPC("lou","m2_crowd_npc1")
			Game.AddNPC("eddie","m2_crowd_npc2")
			Game.AddNPC("wiggum","m2_crowd_npc3")
			Game.SetDestination("m2_escape","triggersphere")
			Game.SetCollectibleEffect("none")
			Game.SetFadeOut(0.1)
		-- Still an easy timer since this whole thing is basically trial and error
		Game.CloseObjective()
		timeLimit[Mode.NormalMode] = 45
		timeLimit[Mode.HardMode] = 30
		Game.SetStageTime(timeLimit[Mode.Current])
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m2_crowd1")
			Game.SetCondThreshold(2.5)
			Game.SetCondMessageIndex(9)
			Game.SetCondDecay(40, 2)	--take a long time to deplete
			--Game.SetCondSound("gag_clnk","enter_trigger")
			--Game.SetCondSound("countdown_beeps","inside_trigger",1,5)
			--Game.SetCondSound("D_Bcrash_Brt_02","exit_trigger")
			Game.SetCondSound("spotted_alert","enter_trigger")
			Game.SetCondSound("hidden_alert","exit_trigger")
		Game.CloseCondition()
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m2_limo_fail")	--instant failure if bart goes toward angry drivers.
		Game.CloseCondition()
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetIrisWipe(0.1)
		Game.SetStageMusicAlwaysOn()
		Game.StageStartMusicEvent("M2_drama")
	Game.CloseStage()
	
	Game.AddStage(0)
		DisableAllCameras()
		Game.SetHUDIcon("w_stad")
		Game.SetStageMessageIndex(13)
		Game.AddStageCharacter("bart", "", "", "current", "m2_car_escape")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m2_stadium", "carsphere")
		Game.CloseObjective()
		timeLimit[Mode.NormalMode] = 20
		timeLimit[Mode.HardMode] = 14
		Game.SetStageTime(timeLimit[Mode.Current])
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m2_crowd1")
			Game.SetCondSound("spotted_alert","enter_trigger")
		Game.CloseCondition()
		Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("some_camera_locator")
		Game.DisableTrigger("m2_camera3")
		Game.AddStageCharacter("bart", "m2_player_cam2", "", "current", "m2_racestart")
		Game.AddStageVehicle("cLimo","m2_limo_after_escape","evade","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerd_after_escape","evade","Missions\\level01\\M2nerd.con","male2")
		Game.AddStageWaypoint("m2_waypoint_after_escape")
		Game.AddObjective("timer")
			Game.SetDurationTime(3)
		Game.CloseObjective()
		Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		Game.SetHUDIcon("w_alley")	--to be made
		Game.SetStageMessageIndex(14)
		Game.AddStageCharacter("bart", "", "", "current", "m2_bart_after_wait")
		Game.AddStageVehicle("cLimo","m2_limo_after_wait","chase","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerd_after_wait","chase","Missions\\level01\\M2nerd.con","male2")
		Game.AddStageVehicle("krust_v","m2_krusty_car","NULL","Missions\\level01\\M2krusty.con")
		Game.AddObjective("goto")
			Game.AddNPC("krusty", "m2_krusty")
			Game.SetDestination("m2_alley", "carsphere")
		Game.CloseObjective()
		timeLimit[Mode.NormalMode] = 30
		timeLimit[Mode.HardMode] = 20
		Game.SetStageTime(timeLimit[Mode.Current])
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m2_crowd1")
			Game.SetCondSound("spotted_alert","enter_trigger")
		Game.CloseCondition()
		Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("some_camera_locator")
		Game.DisableTrigger("m2_camera2")
		Game.AddStageCharacter("bart", "m2_player_cam3", "", "current", "m2_car_alley")
		Game.AddStageVehicle("cLimo","m2_limo_near_alley","evade","Missions\\level01\\M2limo.con","mobstr")
		Game.AddStageVehicle("cNerd","m2_nerd_near_alley","evade","Missions\\level01\\M2nerd.con","male2")
		Game.AddStageVehicle("krust_v","m2_krusty_car","NULL","Missions\\level01\\M2krusty.con")
		Game.AddStageWaypoint("m2_waypoint_near_alley")
		Game.AddStageWaypoint("m2_waypoint_near_alley2")
		Game.AddObjective("timer")
			Game.AddNPC("krusty", "m2_krusty")
			Game.SetDurationTime(4)
		Game.CloseObjective()
		Game.SetIrisWipe(0.1)
		Game.StageStartMusicEvent("M2_start")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage()	--despawn bestman so it starts with full health
		DisableAllCameras()
		Game.AddStageCharacter("bart", "", "", "current", "m2_car_alley")
		Game.AddStageVehicle("cNerd2","m2_nerd_kb","NULL","Missions\\level01\\M2nerddest.con")
		Game.AddStageVehicle("krust_v","m2_krusty_car","NULL","Missions\\level01\\M2krusty.con")
		Game.AddObjective("timer")
			Game.AddNPC("krusty", "m2_krusty")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.ShowStageComplete()
	Game.CloseStage()

	Game.AddStage()
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointDynaLoadData("l5r3.p3d;l5z4.p3d;l5r4.p3d;")
		Game.SetCheckpointResetPlayerInCar( "m2_car_alley" )
		DisableAllCameras()
		Game.SetHUDIcon("w_krust")
		Game.SetStageMessageIndex(15)
		--Game.AddStageCharacter("bart", "", "", "current", "m2_car_alley")
		Game.AddStageVehicle("krust_v","m2_krusty_car","NULL","Missions\\level01\\M2krusty.con")
		Game.AddStageVehicle("cNerd2","m2_nerd_kb","NULL","Missions\\level01\\M2nerddest.con")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.AddNPC("krusty", "m2_krusty")
			Game.AddDriver("male2", "cNerd2")
			Game.SetDestination("m2_kb_police", "carsphere")
		Game.CloseObjective()
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m2_crowd1")
			Game.SetCondSound("spotted_alert","enter_trigger")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		Game.SetHUDIcon("w_bestmn")
		Game.SetStageMessageIndex(16)
		Game.ActivateVehicle("krust_v","NULL","target")	--needs to be in an active state or objectives/conditions can't find it
		Game.ActivateVehicle("cNerd2", "NULL", "chase")
		Game.AddObjective("destroy")
			Game.AddNPC("krusty", "m2_krusty")
			Game.SetObjTargetVehicle("cNerd2")
		Game.CloseObjective()
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m2_crowd1")
			Game.SetCondSound("spotted_alert","enter_trigger")
		Game.CloseCondition()
		Game.AddCondition("followdistance")	--don't want players going back to the police
			Game.SetFollowDistances(0, 175)
			Game.SetCondTargetVehicle("krust_v")
		Game.CloseCondition()
		Game.SetStageTime(60)
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()

	Game.AddStage()
		DisableAllCameras()
		Game.SetHUDIcon("w_krust")
		Game.SetStageMessageIndex(18)
		Game.AddStageVehicle("krust_v","m2_krusty_car","NULL","Missions\\level01\\M2krusty.con")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.AddDriver("krusty", "krust_v")
			Game.RemoveNPC("krusty")
			Game.SetDestination("m2_kb_police", "carsphere")
		Game.CloseObjective()
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m2_crowd1")
			Game.SetCondSound("spotted_alert","enter_trigger")
		Game.CloseCondition()
		Game.AddStageTime(10)
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()

	Game.AddStage()
		DisableAllCameras()
		Game.SetHUDIcon("w_krust")	--placeholder icon. need vehicle icon.
		Game.SetStageMessageIndex(17)
		Game.ActivateVehicle("krust_v", "NULL", "evade")
		Game.AddStageWaypoint("m2_stadium")
		Game.AddObjective("follow")
			Game.SetObjTargetVehicle("krust_v")
		Game.CloseObjective()
		Game.AddCondition("followdistance")
			Game.SetFollowDistances(0, 150)
			Game.SetCondTargetVehicle("krust_v")
		Game.CloseCondition()
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m2_crowd1")
			Game.SetCondSound("spotted_alert","enter_trigger")
		Game.CloseCondition()
		Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage("final")
		DisableAllCameras()
		Game.AddStageCharacter("bart", "m2_bart_stadium_end", "", "current", "m2_car_stadium_end")
		Game.AddObjective("timer")
			Game.RemoveDriver("krust_v")
			Game.AddNPC("krusty", "m2_krusty_stadium")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
	Game.CloseStage()
--[[
	Game.AddStage("final")
		Game.DisableTrigger("some_camera_locator")
		Game.SetHUDIcon( "w_bestmn" )
		Game.SetStageMessageIndex(7)
		Game.SetStageTime(30)
		Game.ActivateVehicle("cNerd","NULL","chase")
		Game.AddObjective("losetail")
			Game.SetObjTargetVehicle("cNerd")
			Game.SetObjDistance(150)
			-- unsure if there is a more efficient way to remove the extra npcs
			--Game.RemoveNPC("male2")
			--Game.RemoveNPC("male4")
			--Game.RemoveNPC("olady2")
			--Game.RemoveNPC("fem3")
		Game.CloseObjective()
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m2_crowd1")
			Game.SetCondSound("spotted_alert","enter_trigger")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	]]

Game.CloseMission()