Game.SelectMission("m2sd")

	Game.SetMissionResetPlayerOutCar("m2_bartstart_sd","m2_carstart_sd")
	Game.SetDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
	Game.StreetRacePropsLoad("l1m1_baracade.p3d;") -- Barracade
	Game.StreetRacePropsUnload("l1m1_baracade.p3d:") -- Barracade
	Game.SetPedsEnabled(1)

	Game.UsePedGroup(5)

	Game.AddStage()
		Game.SetStageMessageIndex(01)
		Game.SetHUDIcon("w_park")
		Game.SetMaxTraffic(5)
		Game.AddObjective("goto")
			Game.SetDestination("m2_phone_goto","carsphere")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.RESET_TO_HERE()
		Game.SetHUDIcon("w_fone")
		Game.SetStageMessageIndex(02)
		Game.AddObjective("goto")
			Game.SetDestination("m2_phone_loc","triggersphere")
			Game.MustActionTrigger()
			Game.SetCollectibleEffect("none")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(1)
		Game.AddObjective("dialogue")
			Game.SetPresentationBitmap( "art/frontend/dynaload/images/mis01_02.p3d" )
			Game.AddNPC("npd","m2_npd_talk_sd")
			Game.AmbientAnimationRandomize( 1, 0 )      -- ( pc=0, npc=1) (nonrandom=0, random=1)
			Game.AmbientAnimationRandomize( 0, 0 )
			Game.SetConversationCam( 0, "npc_far" )
			Game.SetConversationCam( 1, "npc_far" )
			Game.SetConversationCam( 2, "npc_far" )
			Game.SetConversationCam( 3, "npc_far" )
			Game.SetConversationCam( 4, "npc_far" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientPcAnimation( "none" )
			Game.AddAmbientPcAnimation( "dialogue_hands_in_air" )
			Game.AddAmbientPcAnimation( "none" )
			Game.AddAmbientPcAnimation( "dialogue_yes" )
			Game.AddAmbientPcAnimation( "none" )
			Game.SetDialogueInfo("bart","npd","phone3",0)
			Game.SetDialoguePositions("m2_bart_talk_sd","m2_npd_talk_sd","m2_carstart_sd")
		Game.CloseObjective()
	Game.CloseStage()

Game.CloseMission()