Game.SelectMission("m3")

Game.SetMissionResetPlayerInCar("m3_bart_carstart")
Game.SetDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
Game.StreetRacePropsLoad("l1m1_baracade.p3d;") -- Barracade
Game.StreetRacePropsUnload("l1m1_baracade.p3d:") -- Barracade

Game.UsePedGroup(5)

Game.AddStage()
Game.SetStageMessageIndex(12)
Game.AddObjective("getin")
Game.SetObjTargetVehicle("current")
Game.CloseObjective()
if Mode.IsHard then
Game.SetStageTime(10)
Game.AddCondition("timeout")
Game.CloseCondition()
end
Game.CloseStage()

Game.AddStage()
Game.RESET_TO_HERE()
Game.SetStageMessageIndex(03)
Game.SetHUDIcon("w_kburg")
Game.AddObjective("goto")
Game.SetDestination("m3_kburger","carsphere")
Game.CloseObjective()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
if Mode.IsNormal then
Game.SetStageTime(30)
else
Game.SetStageTime(23)
end
Game.AddCondition("timeout")
Game.CloseCondition()
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(4)
Game.SetHUDIcon("w_blend")
-- HUD Icon doesn't exist yet
Game.AddObjective("goto")
Game.SetDestination("m3_item_1","blend")
Game.SetCollectibleEffect("wrench_collect")
Game.CloseObjective()
if Mode.IsHard then
Game.SetStageTime(10)
Game.AddCondition("timeout")
Game.CloseCondition()
end
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(7)
Game.SetHUDIcon("w_dmv")
Game.AddObjective("goto")
Game.SetDestination("m3_dmv","carsphere")
Game.CloseObjective()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
if Mode.IsNormal then
Game.SetStageTime(70)
else
Game.SetStageTime(60)
end
Game.AddCondition("timeout")
Game.CloseCondition()
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(5)
Game.SetHUDIcon("w_pills")
-- HUD Icon doesn't exist yet
Game.AddObjective("goto")
Game.SetDestination("m3_item_2","pills")
Game.SetCollectibleEffect("wrench_collect")
Game.CloseObjective()
if Mode.IsHard then
Game.SetStageTime(10)
Game.AddCondition("timeout")
Game.CloseCondition()
end
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(8)
Game.SetHUDIcon("w_moes")
Game.AddObjective("goto")
Game.SetDestination("m3_moes","carsphere")
Game.CloseObjective()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
if Mode.IsNormal then
Game.SetStageTime(30)
else
Game.SetStageTime(25)
end
Game.AddCondition("timeout")
Game.CloseCondition()
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(6)
Game.SetHUDIcon("w_laser")
-- HUD Icon doesn't exist yet
Game.AddObjective("goto")
Game.SetDestination("m3_item_3","lasergun")
Game.SetCollectibleEffect("wrench_collect")
Game.CloseObjective()
if Mode.IsHard then
Game.SetStageTime(10)
Game.AddCondition("timeout")
Game.CloseCondition()
end
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(1)
Game.SetHUDIcon("w_stad")
Game.AddObjective("goto")
Game.SetDestination("m3_stadium_sd","carsphere")
Game.AddNPC("krusty", "m3_krusty_sd")
Game.CloseObjective()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
if Mode.IsNormal then
Game.SetStageTime(35)
else
Game.SetStageTime(25)
end
Game.AddCondition("timeout")
Game.CloseCondition()
Game.CloseStage()

Game.AddStage(0)
Game.SetStageMessageIndex(02)
Game.SetHUDIcon("w_krust")
Game.AddObjective("talkto")
Game.AddNPC("krusty", "m3_krusty_sd")
Game.AddObjectiveNPCWaypoint("krusty" , "m3_krustywalk_1")
Game.AddObjectiveNPCWaypoint("krusty" , "m3_krustywalk_2")
Game.AddObjectiveNPCWaypoint("krusty" , "m3_krustywalk_3")
Game.AddObjectiveNPCWaypoint("krusty" , "m3_krustywalk_4")
Game.SetTalkToTarget("krusty", 0, 0)
Game.CloseObjective()
Game.CloseStage()

Game.AddStage(1)
Game.AddObjective("dialogue")
Game.AddNPC("krusty", "m3_krusty_sd")
Game.AmbientAnimationRandomize( 1, 0 )
Game.AmbientAnimationRandomize( 0, 0 )
Game.SetConversationCam( 0, "pc_far" )
Game.SetConversationCam( 1, "npc_near" )
Game.SetConversationCam( 2, "pc_far" )
Game.SetConversationCam( 3, "npc_far" )
Game.SetConversationCam( 4, "pc_near" )
Game.AddAmbientNpcAnimation( "dialogue_open_arm_hand_gesture" )
Game.AddAmbientNpcAnimation( "dialogue_shaking_fist" )
Game.AddAmbientNpcAnimation( "dialogue_hands_on_hips" )
Game.AddAmbientNpcAnimation( "dialogue_no" )
Game.AddAmbientNpcAnimation( "dialogue_cross_arms" )
Game.AddAmbientPcAnimation( "dialogue_hands_on_hips" )
Game.AddAmbientPcAnimation( "dialogue_no" )
Game.AddAmbientPcAnimation( "dialogue_scratch_head" )
Game.AddAmbientPcAnimation( "none" )
Game.AddAmbientPcAnimation( "dialogue_hands_in_air" )
Game.SetCamBestSide("m3_bestside")
Game.SetDialogueInfo("bart","krusty","krusty",0)
Game.SetDialoguePositions("m3_bart_talk","m3_krusty_talk","m3_carstart_sd")
Game.CloseObjective()
Game.CloseStage()

Game.AddStage("locked","car","")
Game.CHECKPOINT_HERE()
Game.SetCheckpointDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
Game.SetCheckpointResetPlayerOutCar("m3_bart_talk","m3_bart_carstart")
Game.SetStageMessageIndex(9)
Game.AddObjective("timer")
Game.SetDurationTime(0)
Game.CloseObjective()
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(12)
Game.AddObjective("getin")
Game.SetObjTargetVehicle("current")
Game.CloseObjective()
if Mode.IsHard then
Game.SetStageTime(10)
Game.AddCondition("timeout")
Game.CloseCondition()
end
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(14)
Game.SetHUDIcon("w_park")
Game.AddObjective("goto")
Game.SetDestination("m3_park","carsphere")
Game.AddNPC("npd", "m3_npd")
Game.RemoveNPC("krusty")
Game.CloseObjective()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
if Mode.IsNormal then
Game.SetStageTime(30)
else
Game.SetStageTime(20)
end
Game.AddCondition("timeout")
Game.CloseCondition()
Game.CloseStage()

Game.AddStage()
Game.SetHUDIcon("w_statue")
Game.SetStageMessageIndex(15)
Game.AddObjective("goto")
Game.AddNPC("npd","m3_npd")
Game.SetDestination("m3_tape_1","triggersphere")
Game.MustActionTrigger()
Game.SetCollectibleEffect("none")
Game.CloseObjective()
if Mode.IsHard then
Game.SetStageTime(10)
Game.AddCondition("timeout")
Game.CloseCondition()
end
Game.SetFadeOut(1.0)
Game.SetCompletionDialog("doing")
Game.CloseStage()

Game.AddStage()
Game.StartCountdown("count")
Game.AddToCountdownSequence( "o", 3000 )
Game.SetStageMessageIndex(12)
Game.SetStageAllowMissionCancel(0)
Game.AddObjective("timer")
Game.SetDurationTime(3.0)
Game.StayInBlack()
Game.CloseObjective()
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(12)
Game.AddObjective("getin")
Game.SetObjTargetVehicle("current")
Game.CloseObjective()
if Mode.IsHard then
Game.SetStageTime(10)
Game.AddCondition("timeout")
Game.CloseCondition()
end
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(10)
Game.SetHUDIcon("w_statio")
Game.AddObjective("goto")
Game.SetDestination("m3_kburger","carsphere")
Game.RemoveNPC("krusty")
Game.CloseObjective()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current" )
Game.CloseCondition()
if Mode.IsNormal then
Game.SetStageTime(40)
else
Game.SetStageTime(30)
end
Game.AddCondition("timeout")
Game.CloseCondition()
Game.CloseStage()

Game.AddStage()
Game.SetHUDIcon("w_sign")
Game.SetStageMessageIndex(16)
Game.AddObjective("goto")
Game.AddNPC("npd","m3_npd")
Game.SetDestination("m3_tape_2","triggersphere")
Game.MustActionTrigger()
Game.SetCollectibleEffect("none")
Game.CloseObjective()
if Mode.IsHard then
Game.SetStageTime(10)
Game.AddCondition("timeout")
Game.CloseCondition()
end
Game.SetFadeOut(1.0)
Game.SetCompletionDialog("kkk")
Game.CloseStage()

Game.AddStage()
Game.StartCountdown("count")
Game.AddToCountdownSequence( "o", 7000 )
Game.SetStageAllowMissionCancel(0)
Game.AddObjective("timer")
Game.SetDurationTime(7.0)
Game.StayInBlack()
Game.CloseObjective()
Game.CloseStage()

Game.AddStage()
Game.CHECKPOINT_HERE()
Game.SetCheckpointDynaLoadData("l5z4.p3d;l5r3.p3d;l5r4.p3d;")
Game.SetCheckpointResetPlayerInCar("m3_racestart" )
Game.SetHUDIcon( "w_race" )
Game.SetStageMessageIndex(17)
Game.DisableHitAndRun()
Game.AddStageCharacter("bart", "", "", "current", "m3_racestart")
Game.StartCountdown("count")
Game.AddToCountdownSequence( "3", 800 ) -- duration time in milliseconds
Game.AddToCountdownSequence( "2", 800 ) -- duration time in milliseconds
Game.AddToCountdownSequence( "1", 600 ) -- duration time in milliseconds
Game.AddToCountdownSequence( "GO", 400 ) -- duration time in milliseconds
Game.NoTrafficForStage()
Game.AddStageVehicle(Car2,"m3_raceai_3","race","Missions\\level01\\m3_1stNORM.con","krusty")
Game.AddStageVehicle(Car,"m3_raceai_2","race","Missions\\level01\\m3_2ndNORM.con","male1")
Game.AddStageVehicle(Car3,"m3_raceai_1","race","Missions\\level01\\m3_1stNORM.con","male4")
Game.AddStageWaypoint( "m3_navwp_1" )
Game.AddStageWaypoint( "m3_navwp_2" )
Game.AddStageWaypoint( "m3_navwp_3" )
Game.AddStageWaypoint( "m3_navwp_4" )
Game.AddStageWaypoint( "m3_navwp_5" )
Game.AddStageWaypoint( "m3_navwp_6" )
Game.AddStageWaypoint( "m3_navwp_7" )
Game.AddStageWaypoint( "m3_navwp_8" )
Game.AddStageWaypoint( "m3_navwp_9" )
Game.AddStageWaypoint( "m3_navwp_10" )
Game.AddStageWaypoint( "m3_navwp_10b" )
Game.AddStageWaypoint( "m3_navwp_11" )
Game.AddStageWaypoint( "m3_navwp_final" )
Game.AddObjective( "race")
Game.AddNPC("krusty", "m3_krusty_sd")
Game.AddCollectible("m3_racewp_1","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_2","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_3","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_4","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_5","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_6","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_7","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_8","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_9","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_10","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_11","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_12","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_16","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.AddCollectible("m3_racewp_final","carsphere")
Game.SetCollectibleEffect("wrench_collect")
Game.CloseObjective()
Game.AddCondition("position")
Game.SetConditionPosition(1)
Game.CloseCondition()
Game.AddCondition( "damage" )
Game.SetCondMinHealth( 0.0 )
Game.SetCondTargetVehicle( "current")
Game.CloseCondition()
Game.AddCondition("outofvehicle")
Game.SetCondTime( 10000 )
Game.CloseCondition()
Game.SetFadeOut(1.0)
Game.CloseStage()

Game.AddStage()
Game.SetStageAllowMissionCancel(0)
Game.AddStageCharacter("bart", "m3_bart_talk", "", "current", "m3_carstart_sd")
Game.AddObjective("timer")
Game.AddNPC("krusty", "m3_krusty_talk")
Game.SetDurationTime(1)
Game.StayInBlack()
Game.CloseObjective()
Game.CloseStage()

Game.AddStage()
Game.SetStageMessageIndex(18)
Game.SetHUDIcon("w_krust")
Game.AddObjective("hitpeds")
Game.AddNPC("krusty", "m3_krusty_talk")
Game.AddObjTargetModel("krusty")
Game.SetObjTotal(3)
Game.CloseObjective()
Game.CloseStage()

Game.AddStage("final")
Game.StartCountdown("count")
Game.AddToCountdownSequence( "o", 100 )
Game.AddObjective("timer")
Game.SetDurationTime(0.1)
Game.CloseObjective()
Game.CloseStage()

Game.CloseMission()