local function KbossCars()
	Game.AddStageVehicle("krust_v", "m3_raceai_1", "NULL", "Missions\\level01\\m3_race1st.con", "krusty")
	Game.AddStageVehicle("krust2","m3_raceai_2","NULL","Missions\\level01\\m3_race2nd.con","male1")
	Game.AddStageVehicle("kboss","m3_raceai_3","NULL","Missions\\level01\\m3_race3rd.con","male4")
end

Game.SelectMission("m3")

	Game.SetMissionResetPlayerInCar("m3_carstart_sd")
	Game.SetDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
	Game.StreetRacePropsLoad("l1m1_baracade.p3d;") -- Barracade
	--Game.StreetRacePropsUnload("l1m1_baracade.p3d:") -- Barracade
	Game.SetPedsEnabled(1)

	Game.UsePedGroup(5)
	Game.SetNumValidFailureHints( Mode.FailHintCount )
	
	if GetSetting("ScrapBookMode") then
		Game.AddStage()
			Game.CHECKPOINT_HERE()
			Game.SetCheckpointDynaLoadData("l5z4.p3d;l5r3.p3d;l5z3.p3d;")
			Game.SetCheckpointResetPlayerInCar("m3_race_restart" )
			Game.NoTrafficForStage()
			KbossCars()
			Game.AddObjective("dummy")
			Game.CloseObjective()
		Game.CloseStage()
		Game.CloseMission()
		return
	end

	Game.AddStage()
		Game.SetStageMessageIndex(12)
		Game.AddObjective("getin")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.RESET_TO_HERE()
		Game.SetStageMessageIndex(3)
		Game.SetHUDIcon("w_kbur2")
		Game.AddObjective("goto")
			Game.SetDestination("m3_higher_district", "upwardglow")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
		Game.SetCondMinHealth( 0.0 )
		Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		--SetTimeByDifficulty(100, 75)
		SetTimeByDifficulty(35, 25)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		-- too early for checkpoint notif
	Game.CloseStage()

	Game.AddStage()
		Game.CHECKPOINT_HERE()	--what are the odds someone restarts here?
		Game.SetCheckpointDynaLoadData("l5r3.p3d;l5z4.p3d;l5r4.p3d;")
		Game.SetCheckpointResetPlayerInCar("m3_restart_higher")
		Game.SetStageMessageIndex(4)
		Game.SetHUDIcon("w_m3item")	--can't decide whether to use a single item icon or a bunch icon.
		Game.AddObjective("delivery", "neither")
			local itemList = {"blend", "pills", "r_choco", "is_comic", "jeans"}
			local x = 1
			for i=1, 20 do
				Game.AddCollectible("m3_item_" .. i, itemList[x])
				x = x + 1
				if x > #itemList then
					x = 1
				end
			end
		Game.CloseObjective()
		Game.AddCondition( "damage" )
		Game.SetCondMinHealth( 0.0 )
		Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		--Game.AddStageTime(-1)
		
		SetTimeByDifficulty(80, 60)
		Game.IfCurrentCheckpoint()
			SetTimeByDifficulty(82, 62)
		Game.EndIf()
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.SetStageMessageIndex(5)
		Game.SetHUDIcon("w_kbur2")
		Game.AddObjective("goto")
			Game.SetDestination("m3_kburger_tape","upwardglow")
		Game.CloseObjective()
		Game.AddStageTime(15)
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()

	Game.AddStage()
		Game.SetHUDIcon("w_audiotape")
		Game.SetStageMessageIndex(6)
		Game.AddObjective("goto", "neither")
			Game.SetDestination("m3_tape_2","audiotape")
			Game.MustActionTrigger()
			Game.SetCollectibleEffect("none")
		Game.CloseObjective()
		--Game.SetFadeOut(1.0)
		Game.SetCompletionDialog("popcorn")
	Game.CloseStage()
	
	Game.AddStage()
		Game.ResetStageHitAndRun()
		Game.SetStageAllowMissionCancel(0)
		LockPlayer(5.0)
		Game.AddObjective("timer")
			Game.SetDurationTime(5.2)
			--Game.StayInBlack()
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.SetStageMessageIndex(7)
		Game.SetHUDIcon("w_stad")
		Game.SetMaxTraffic(5)
		Game.AddObjective("goto")
			Game.SetDestination("m3_stadium_sd","upwardglow")
			Game.AddNPC("krusty", "m3_krusty_sd")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		SetTimeByDifficulty(40, 30)
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()

	Game.AddStage(0)
		Game.SetStageMessageIndex(2)
		Game.SetHUDIcon("w_krust")
		Game.AddObjective("talkto")
			Game.AddNPC("krusty", "m3_krusty_sd")
			for i= 1,4 do
			Game.AddObjectiveNPCWaypoint("krusty" , "m3_krustywalk_"..i)
			end
		Game.SetTalkToTarget("krusty", 0, 0)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage("locked", "car", "")
		Game.SetStageMessageIndex(9)
		Game.AddObjective("dialogue")
			Game.AddNPC("krusty", "m3_krusty_sd")
			Game.AmbientAnimationRandomize( 1, 0 )
			Game.AmbientAnimationRandomize( 0, 0 )
			Game.SetConversationCam( 0, "npc_far" )
			Game.SetConversationCam( 1, "pc_near" )
			Game.SetConversationCam( 2, "npc_far" )
			Game.SetConversationCam( 3, "pc_near" )
			--Game.SetConversationCam( 4, "pc_near" )	--hbn dialog skips camera and animations
			Game.SetConversationCam( 4, "npc_near" )
			Game.SetConversationCam( 5, "npc_near" )
			Game.AddAmbientNpcAnimation( "dialogue_open_arm_hand_gesture" )
			Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientNpcAnimation( "dialogue_cross_arms" )
			Game.AddAmbientNpcAnimation( "none" )
			--Game.AddAmbientNpcAnimation( "none" )
			Game.AddAmbientNpcAnimation( "dialogue_shaking_fist" )
			Game.AddAmbientPcAnimation( "dialogue_cross_arms" )
			Game.AddAmbientPcAnimation( "none" )
			Game.AddAmbientPcAnimation( "none" )
			Game.AddAmbientPcAnimation( "dialogue_shake_hand_in_air" )
			--Game.AddAmbientPcAnimation( "dialogue_shake_hand_in_air" )
			Game.AddAmbientPcAnimation( "none" )
			Game.SetCamBestSide("m3_bestside")
			Game.SetDialogueInfo("bart","krusty","krustylied",0)
			Game.SetDialoguePositions("m3_bart_talk","m3_krusty_talk","m3_carstart_sd")
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()	-- empty stage because objective text doesn't show after locked stage message.
		Game.AddObjective("timer")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.ShowStageComplete()
	Game.CloseStage()

	Game.AddStage()
		Game.CHECKPOINT_HERE()	--what are the odds someone restarts here?
		Game.SetCheckpointDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
		Game.SetCheckpointResetPlayerOutCar("m3_bart_talk", "m3_restart1")
		Game.SetStageMessageIndex(12)
		Game.AddObjective("getin")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.CHECKPOINT_HERE()	--i don't want to hear "thunk thunk" when i restart
		Game.SetCheckpointDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
		Game.SetCheckpointResetPlayerInCar("m3_restart1")
		Game.SetStageMessageIndex(8)
		Game.SetHUDIcon("w_park")
		Game.AddObjective("goto")
			Game.AddNPC("krusty", "m3_krusty_sd")
			Game.SetDestination("m3_park","upwardglow")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		SetTimeByDifficulty(30, 20)
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()

	Game.AddStage()
		Game.SetHUDIcon("w_audiotape")
		Game.SetStageMessageIndex(9)
		Game.AddObjective("goto")
			Game.RemoveNPC("krusty")
			Game.SetDestination("m3_tape_1","audiotape")
			Game.MustActionTrigger()
			Game.SetCollectibleEffect("none")
		Game.CloseObjective()
		Game.AddStageTime(-1)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		--Game.SetFadeOut(1.0)
		Game.SetCompletionDialog("doing")
	Game.CloseStage()

	Game.AddStage()
		Game.ResetStageHitAndRun()
		LockPlayer(3.5)
		Game.SetStageAllowMissionCancel(0)
		Game.AddObjective("timer")
			Game.RemoveNPC("krusty")
			Game.SetDurationTime(3.8)
			--Game.StayInBlack()
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.SetStageMessageIndex(1)
		Game.SetHUDIcon("w_stad")
		Game.AddStageVehicle("krust_v", "m3_krustycar_stadium", "NULL", "Missions\\level01\\m3_race1st.con", "krusty")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m3_stadium_big","upwardglow")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		SetTimeByDifficulty(25, 17)
		Game.AddCondition("timeout")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.SetStageMessageIndex(10)
		Game.SetHUDIcon("w_krustc")	--need krust_v icon
		Game.ActivateVehicle("krust_v", "NULL", "evade")
		Game.AddStageVehicle("krust2","m3_raceai_2","NULL","Missions\\level01\\m3_race2nd.con","male1")
		Game.AddStageVehicle("kboss","m3_raceai_3","NULL","Missions\\level01\\m3_race3rd.con","male4")
		for i=1, 2 do
			Game.AddStageWaypoint("m3_follow_wp" .. i)
		end
		Game.SetMaxTraffic(2)
		Game.AddObjective("follow")
			Game.SetObjTargetVehicle("krust_v")
		Game.CloseObjective()
		Game.AddCondition( "followdistance" )
			Game.SetFollowDistances( 0, 150 )
			Game.SetCondTargetVehicle( "krust_v" )
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage() -- Use Function "KbossCars()"
		Game.NoTrafficForStage()
		KbossCars()
		Game.AddStageCharacter("bart", "", "", "current", "m3_race_restart")
		LockPlayer(1)
		Game.AddObjective("timer")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage("locked", "car", "")
		Game.NoTrafficForStage()
		Game.SetStageMessageIndex(10)
		KbossCars()
		LockPlayer(1)
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.NoTrafficForStage()
		KbossCars()
		LockPlayer(1)
		Game.AddObjective("timer")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.ShowStageComplete()
	Game.CloseStage()

	Game.AddStage()
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointDynaLoadData("l5z4.p3d;l5r3.p3d;l5z3.p3d;")
		Game.SetCheckpointResetPlayerInCar("m3_race_restart" )
		Game.SetHUDIcon( "w_audiotape" )	--could this be an icon of the audio tape?
		Game.SetStageMessageIndex(11)
		Game.DisableHitAndRun()
		Game.StartCountdown("count")
		Game.AddToCountdownSequence( "3", 800 ) -- duration time in milliseconds
		Game.AddToCountdownSequence( "2", 800 ) -- duration time in milliseconds
		Game.AddToCountdownSequence( "1", 800 ) -- duration time in milliseconds
		Game.AddToCountdownSequence( "GO", 400 ) -- duration time in milliseconds
		Game.NoTrafficForStage()
		
		--[[
		Game.AddStageVehicle(Car2,"m3_raceai_3","race","Missions\\level01\\m3_race1st.con","krusty")
		Game.SetVehicleAIParams(Car2, -10, -9)
		Game.AddStageVehicle(Car,"m3_raceai_2","race","Missions\\level01\\m3_race2nd.con","male1")
		Game.SetVehicleAIParams(Car, -10, -9)
		Game.AddStageVehicle(Car3,"m3_raceai_1","race","Missions\\level01\\m3_race3rd.con","male4")
		Game.SetVehicleAIParams(Car3, -10, -9)
		
		if Mode.IsHard then
			Game.SetVehicleAIParams(Car, 50, 51)
			Game.SetVehicleAIParams(Car2, 50, 51)
			Game.SetVehicleAIParams(Car3, 50, 51)
		else
			Game.SetVehicleAIParams(Car, -10, -9)
			Game.SetVehicleAIParams(Car2, -10, -9)
			Game.SetVehicleAIParams(Car3, -10, -9)
		end
		]]
		
		Game.ActivateVehicle("krust_v","NULL","race")
		Game.ActivateVehicle("krust2","NULL","race")
		Game.ActivateVehicle("kboss","NULL","race")
		Game.SetVehicleAIParams("krust_v", -10, -9)
		Game.SetVehicleAIParams("krust2", -10, -9)
		Game.SetVehicleAIParams("kboss", -10, -9)
		
		if Mode.IsHard then
			Game.SetStageAIRaceCatchupParams("krust_v", 80, 0.7, 1.1, 1.2)
			Game.SetStageAIRaceCatchupParams("krust2", 80, 0.6, 1.1, 1.2)
			Game.SetStageAIRaceCatchupParams("kboss", 80, 0.7, 1.1, 1.1)
		else
			Game.SetStageAIRaceCatchupParams("krust_v", 80, 0.6, 0.95, 1.1)
			Game.SetStageAIRaceCatchupParams("krust2", 80, 0.5, 0.95, 1.1)
			Game.SetStageAIRaceCatchupParams("kboss", 80, 0.6, 0.95, 1.0)
		end
		
		for i, navPoint in ipairs({1,2,4,5,6}) do
			Game.AddStageWaypoint("m3_navwp_"..navPoint)
		end
		Game.AddStageWaypoint( "m3_navwp_final2" )
		Game.AddObjective( "race", "neither")
			Game.AddNPC("krusty", "m3_krusty_sd")
			for i= 3,8 do
			Game.AddCollectible("m3_racewp_"..i,"upwardglow_b")
			end
			Game.AddCollectible("m3_racewp_final2","audiotape")
		Game.CloseObjective()
		Game.AddCondition("position")
			Game.SetConditionPosition(1)
		Game.CloseCondition()
		SurviveConditions()
		Game.SetFadeOut(1.0)
		Game.SetCompletionDialog("kkk")
	Game.CloseStage()
	
	Game.AddStage()
		Game.SetStageAllowMissionCancel(0)
		LockPlayer(4.9)
		Game.AddStageVehicle("krust_v", "m3_krustycar_end", "NULL", "Missions\\level01\\m3_race1st.con")
		Game.AddStageCharacter("bart", "m3_bart_end", "", "current", "m3_car_end")
		Game.AddObjective("timer")
			Game.RemoveDriver("krusty")
			Game.AddNPC("krusty", "m3_krusty_end")
			Game.SetDurationTime(5.1)
			Game.StayInBlack()
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.EnableHitAndRun()
		Game.AddStageVehicle("krust_v", "m3_krustycar_end", "NULL", "Missions\\level01\\m3_race1st.con")
		Game.AddStageCharacter("bart", "m3_bart_end", "", "current", "m3_car_end")
		Game.SetMaxTraffic(5)
		LockPlayer(1.9)
		Game.AddObjective("timer")
			Game.AddNPC("krusty", "m3_krusty_end")
			Game.SetDurationTime(2.0)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.SetStageMessageIndex(13)
		Game.SetHUDIcon("w_krust")
		Game.SetMaxTraffic(5)
		Game.AddStageVehicle("krust_v", "m3_krustycar_end", "NULL", "Missions\\level01\\m3_race1st.con")
		--Game.AddStageCharacter("bart", "m3_bart_end", "", "current", "m3_car_end")
		Game.AddObjective("hitpeds")
			Game.AddNPC("krusty", "m3_krusty_end")
			Game.AddObjTargetModel("krusty")
			Game.SetObjTotal(3)
		Game.CloseObjective()
		--[[
		Game.SetStageTime(20)	--hit him before krusty runs away
		Game.AddCondition("timeout")
		Game.CloseCondition()
		]]	--changed my mind.
	Game.CloseStage()

	Game.AddStage("final")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
	Game.CloseStage()

Game.CloseMission()