local billboardTable = {"r2", "r3", "z4"}
local function ChangeBillboardTexture(region)
	local BillboardToDisable = {}
	for i, region in ipairs(billboardTable) do
		table.insert(BillboardToDisable, region)
	end
	
	local indexOfRegion = 0
	for i, billboard in ipairs(BillboardToDisable) do
		if billboard == region then
			indexOfRegion = i
			break
		end
	end
	
	--if indexOfRegion < 1 then return end
	
	table.remove(BillboardToDisable, indexOfRegion)
	for i, billboard in ipairs(BillboardToDisable) do
		Game.DisableTrigger("m5_add_graffiti_" .. billboard .. "_mission")
	end
end

local function NoBillboardChange()
	for i, billboard in ipairs(billboardTable) do
		Game.DisableTrigger("m5_add_graffiti_" .. billboard .. "_mission")
	end
end

local function DisableAllCameras()
	for i=1, 8 do
		Game.DisableTrigger("m5_cam" .. i)
	end
end

local function EnableCamera(tableIndex)
	local CamToDisable = {1, 2, 3, 4, 5, 6, 7, 8}
	table.remove(CamToDisable, tableIndex)
	for i, cam in ipairs(CamToDisable) do
		Game.DisableTrigger("m5_cam" .. cam)
	end
end

local function RetainTimer()
	Game.AddStageTime(-1)
	Game.AddCondition("timeout")
	Game.CloseCondition()
end

local crowdLocator = "m5_crowd_npc"
local function AddCrowdNPCs(crowdIndex, crowdNPC1, crowdNPC2, crowdNPC3, crowdNPC4)
	Game.AddNPC(crowdNPC1, crowdLocator .. crowdIndex .. "-1")
	Game.AddNPC(crowdNPC2, crowdLocator .. crowdIndex .. "-2")
	Game.AddNPC(crowdNPC3, crowdLocator .. crowdIndex .. "-3")
	Game.AddNPC(crowdNPC4, crowdLocator .. crowdIndex .. "-4")
end

local durationTime = {3, 3}
local outsideThreshold = {10, 10}

Game.SelectMission("m5")

	Game.SetMissionResetPlayerInCar("m5_carstart")
	Game.SetDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")

	Game.UsePedGroup(5)
	Game.SetNumValidFailureHints( Mode.FailHintCount )

	--the ones already in the map files don't appear in m5 or m5sd
	Game.StreetRacePropsLoad("m5_graffiti.p3d;")
	Game.StreetRacePropsUnload("m5_graffiti.p3d:")
	Game.SetPedsEnabled(1)

	if GetSetting("ScrapBookMode") then
		Game.AddStage()
			Game.CHECKPOINT_HERE()
			Game.SetCheckpointDynaLoadData("l5z3.p3d;l5r3.p3d;l5z4.p3d;")
			Game.SetCheckpointResetPlayerInCar("m5_bart_billboard2")
			DisableAllCameras()
			ChangeBillboardTexture("r3")
			Game.NoTrafficForStage()
			Game.AddObjective("timer")
				Game.SetDurationTime(0.2)
			Game.CloseObjective()
		Game.CloseStage()
		
		Game.AddStage()
			EnableCamera(2)
			ChangeBillboardTexture("r3")
			Game.NoTrafficForStage()
			Game.AddObjective("dummy")
			Game.CloseObjective()
		Game.CloseStage()
		Game.CloseMission()
		return
	end

	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(12)
		Game.AddObjective("getin")
			Game.AddNPC("npd","hidden_npc")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.RESET_TO_HERE()
		DisableAllCameras()
		--NoBillboardChange()
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(13)
		Game.SetHUDIcon("w_court")
		Game.AddObjective("goto")
			AddCrowdNPCs(1, "male6", "cbg", "fem1", "fem4")
			Game.SetDestination("m5_crowd_court","upwardglow")
		Game.CloseObjective()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		Game.SetStageMessageIndex(14)
		Game.SetHUDIcon("w_pedm5")
		Game.AddObjective("insidetrigger")
			AddCrowdNPCs(1, "male6", "cbg", "fem1", "fem4")
			Game.SetObjTrigger("m5_crowd_court_inside")
			Game.SetObjThreshold(4)
		Game.CloseObjective()
		Game.AddCondition("outsidetrigger")
			--Game.SetCondMessageIndex(15)
			Game.SetCondTrigger("m5_crowd_court_inside")
			Game.SetCondThreshold(10)
			--Game.SetCondDecay(20, 1)
		Game.CloseCondition()
		SurviveConditions()
		-- too early for checkpoint notif
	Game.CloseStage()
	
	Game.AddStage()
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")
		Game.SetCheckpointResetPlayerInCar("m5_checkpoint1")
		DisableAllCameras()
		NoBillboardChange()
		Game.SetStageMessageIndex(10)
		Game.SetHUDIcon("w_train")
		Game.AddStageVehicle("homer_v", "m5_homer_moes", "NULL", "Missions\\level01\\M5homer.con", "homer")
		Game.AddStageVehicle("moe_v","m5_moe","NULL","Missions\\level01\\M5moe.con", "moe")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m5_moe_chase_start","upwardglow")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		SetTimeByDifficulty(40, 30)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.SetCompletionDialog("nobeer","moe")
	Game.CloseStage()
	

	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		Game.SetHUDIcon( "w_moecar" )
		Game.SetStageMessageIndex(04)
		Game.AddStageVehicle("cPolic3", "m5_wiggum_trainyard", "NULL", "Missions\\level01\\M5wiggum.con", "wiggum")
		Game.ActivateVehicle("homer_v", "NULL", "evade")	--homer leaves after ruining beer delivery
		Game.ActivateVehicle("moe_v","NULL","chase")
		Game.SetVehicleAIParams("homer_v", -10, -9)
		for i = 1, 4 do
			Game.AddStageWaypoint("m5_homer_path1-" .. i)
		end
		Game.AddObjective("losetail")
			Game.SetObjTargetVehicle("moe_v")
			Game.SetObjDistance(150)
		Game.CloseObjective()
		Game.AddStageTime(19)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.SetCompletionDialog("notv","moe")
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		Game.SetStageMessageIndex(10)
		Game.SetHUDIcon("w_train")
		Game.AddStageVehicle("cPolic3", "m5_wiggum_trainyard", "NULL", "Missions\\level01\\M5wiggum.con", "wiggum")
		Game.AddObjective("goto")
			Game.SetDestination("m5_billboard_trainyard","upwardglow")
		Game.CloseObjective()
		SurviveConditions()
		Game.SetStageTime(60)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetFadeOut(2)
		Game.SetCompletionDialog("spray2")
	Game.CloseStage()
	
	--[[
	Game.AddStage()
		NoBillboardChange()
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(09)
		Game.SetHUDIcon("w_billb1")
		Game.AddObjective("goto")
			Game.SetDestination("m5_poster2","triggersphere")
		Game.CloseObjective()
		SurviveConditions()
		if Mode.IsHard then
		RetainTimer()
		end
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		NoBillboardChange()
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(06)
		Game.SetHUDIcon("w_billb1")
		Game.AddObjective("insidetrigger")
			Game.SetObjTrigger("Poster2Obj")
			Game.SetObjThreshold(4)
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		if Mode.IsHard then
		Game.AddStageTime(-1)
		else
		Game.SetStageTime(15)
		end
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	]]
	
	Game.AddStage()
		EnableCamera(1)
		ChangeBillboardTexture("r2")
		Game.NoTrafficForStage()
		Game.ResetStageHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "", "", "current", "m5_bart_billboard1")
		Game.AddObjective("timer")
			Game.SetDurationTime(2.5)
			Game.StayInBlack()
		Game.CloseObjective()
		SurviveConditions()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		EnableCamera(1)
		ChangeBillboardTexture("r2")
		Game.NoTrafficForStage()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "", "", "current", "m5_bart_billboard1")
		Game.AddObjective("timer")
			Game.SetDurationTime(2.5)
		Game.CloseObjective()
		SurviveConditions()
		Game.SetStageMusicAlwaysOn()
		Game.SetCompletionDialog("limoarrive")
	Game.CloseStage()
	
	Game.AddStage()
		EnableCamera(7)
		Game.NoTrafficForStage()
		Game.SetStageAllowMissionCancel(0)
		Game.AddStageVehicle("cPolic3", "m5_wiggum_trainyard", "NULL", "Missions\\level01\\M5wiggum.con", "wiggum")
		Game.AddStageVehicle("cLimo2","m5_limo_billboard1-1","chase","Missions\\level01\\M5limo.con", "mobstr")
		Game.AddStageCharacter("bart", "m5_bart_cam7", "", "current", "m5_bart_billboard1")
		Game.AddObjective("timer")
			durationTime[Mode.NormalMode] = 3.25
			durationTime[Mode.HardMode] = 2.75
			Game.SetDurationTime( durationTime[Mode.Current] )
		Game.CloseObjective()
		SurviveConditions()
		Game.StageStartMusicEvent("M5_start")
		Game.SetStageMusicAlwaysOn()
		Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		ChangeBillboardTexture("r2")
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(19)
		Game.SetHUDIcon("w_save")
		Game.AddStageCharacter("bart", "", "", "current", "m5_bart_billboard1")
		Game.ActivateVehicle("cPolic3", "NULL", "target")	--despawn after stage
		Game.AddStageVehicle("cLimo2","m5_limo_billboard1-2","chase","Missions\\level01\\M5limo.con", "mobstr")
		Game.AddObjective("goto")
			AddCrowdNPCs(2, "boy3", "barney", "boy2", "boy1")
			Game.SetDestination("m5_crowd_trynsave","upwardglow")
		Game.CloseObjective()
		SetTimeByDifficulty(30, 20)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		Game.SetStageMessageIndex(20)
		Game.SetHUDIcon("w_pedm5")
		--Game.ActivateVehicle("cLimo2", "NULL", "chase")
		Game.AddStageVehicle("cLimo2","m5_limo_trynsave","chase","Missions\\level01\\M5limo.con", "mobstr")
		Game.AddObjective("insidetrigger")
			AddCrowdNPCs(2, "boy3", "barney", "boy2", "boy1")
			Game.SetObjTrigger("m5_crowd_trynsave_inside")
			Game.SetObjThreshold(10)
		Game.CloseObjective()
		Game.AddCondition("outsidetrigger")
			Game.SetCondMessageIndex(15)
			Game.SetCondTrigger("m5_crowd_trynsave_inside")
			Game.SetCondThreshold(outsideThreshold[Mode.Current])
			--Game.SetCondDecay(10, 1)
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		Game.SetHUDIcon( "w_limo" )
		Game.SetStageMessageIndex(16)
		Game.ActivateVehicle("cLimo2","NULL","chase")
		Game.AddObjective("losetail")
			Game.SetObjTargetVehicle("cLimo2")
			Game.SetObjDistance(150)
		Game.CloseObjective()
		SetTimeByDifficulty(60, 45)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		Game.SetStageMessageIndex(7)
		Game.SetHUDIcon("w_highwy")
		Game.AddObjective("goto")
			Game.SetDestination("m5_billboard_highway","upwardglow")
		Game.CloseObjective()
		Game.SetStageTime(60)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.SetFadeOut(2)
		Game.SetCompletionDialog("spray")
	Game.CloseStage()
	
	--[[
	Game.AddStage()
		DisableAllPostersStage2()
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(09)
		Game.SetHUDIcon("w_billb2")
		Game.AddObjective("goto")
			Game.SetDestination("m5_poster1","triggersphere")
		Game.CloseObjective()
		SurviveConditions()
		RetainTimer()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllPostersStage2()
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(06)
		Game.SetHUDIcon("w_billb2")
		Game.AddObjective("insidetrigger")
			Game.SetObjTrigger("Poster1Obj")
			Game.SetObjThreshold(4)
		Game.CloseObjective()
		SurviveConditions()
		RetainTimer()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	]]
	
	Game.AddStage()
		EnableCamera(2)
		ChangeBillboardTexture("r3")
		Game.NoTrafficForStage()
		Game.ResetStageHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "", "", "current", "m5_bart_billboard2")
		Game.AddObjective("timer")
			Game.SetDurationTime(2.5)
			Game.StayInBlack()
		Game.CloseObjective()
		SurviveConditions()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		EnableCamera(2)
		ChangeBillboardTexture("r3")
		--Game.NoTrafficForStage()
		LockPlayer(1.8)
		Game.AddStageCharacter("bart", "", "", "current", "m5_bart_billboard2")
		Game.AddObjective("timer")
			Game.SetDurationTime(2)
		Game.CloseObjective()
		SurviveConditions()
		Game.SetStageMusicAlwaysOn()
		Game.ShowStageComplete()
	Game.CloseStage()
	
	--[[
	Game.AddStage()
		Game.DisableTrigger("Poster3Loc")
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(07)
		Game.SetHUDIcon("w_highwy")
		Game.AddObjective("goto")
			Game.SetDestination("m5_highway","upwardglow")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddStageTime(55)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster3Loc")
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(09)
		Game.SetHUDIcon("w_billb3")
		Game.AddObjective("goto")
			Game.SetDestination("m5_poster3","triggersphere")
		Game.CloseObjective()
		SurviveConditions()
		RetainTimer()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster3Loc")
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(06)
		Game.SetHUDIcon("w_billb3")
		Game.AddObjective("insidetrigger")
			Game.SetObjTrigger("Poster3Obj")
			Game.SetObjThreshold(4)
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		RetainTimer()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	]]
	
	--[[
	Game.AddStage()
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointDynaLoadData("l5z3.p3d;l5r3.p3d;l5z4.p3d;")
		Game.SetCheckpointResetPlayerInCar("m5_bart_billboard2-1")
		DisableAllCameras()
		ChangeBillboardTexture("r3")	--in case players restart here
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(5)
		Game.SetHUDIcon("w_center")
		Game.AddStageVehicle("cLimo2","m5_limo","NULL","Missions\\level01\\M5limo.con", "mobstr")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m5_limo_chase_start","upwardglow")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.SetStageTime(35)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		SetTrafficByDifficulty(3, 5)
		Game.SetHUDIcon( "w_limo" )
		Game.SetStageMessageIndex(16)
		Game.ActivateVehicle("cLimo2","NULL","chase")
		Game.AddObjective("losetail")
			Game.SetObjTargetVehicle("cLimo2")
			Game.SetObjDistance(150)
		Game.CloseObjective()
		Game.SetStageTime(40)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	]]
	
	Game.AddStage()
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointDynaLoadData("l5z3.p3d;l5r3.p3d;l5z4.p3d;")
		Game.SetCheckpointResetPlayerInCar("m5_bart_billboard2-1")
		DisableAllCameras()
		ChangeBillboardTexture("r3")
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(5)
		Game.SetHUDIcon("w_center")
		Game.AddObjective("goto")
			Game.SetDestination("m5_billboard_snr","upwardglow")
		Game.CloseObjective()
		SetTimeByDifficulty(40, 30)
		Game.IfCurrentCheckpoint()
			SetTimeByDifficulty(38, 28)
		Game.EndIf()
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.SetFadeOut(2)
		Game.SetCompletionDialog("spray2")
	Game.CloseStage()
	
	Game.AddStage()
		EnableCamera(3)
		ChangeBillboardTexture("z4")
		Game.NoTrafficForStage()
		Game.ResetStageHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "", "", "current", "m5_bart_billboard3")
		Game.AddObjective("timer")
			Game.SetDurationTime(2.5)
			Game.StayInBlack()
		Game.CloseObjective()
		SurviveConditions()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		EnableCamera(3)
		ChangeBillboardTexture("z4")
		Game.NoTrafficForStage()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "", "", "current", "m5_bart_billboard3")
		Game.AddObjective("timer")
			Game.SetDurationTime(2)
		Game.CloseObjective()
		SurviveConditions()
		Game.SetStageMusicAlwaysOn()
		Game.SetCompletionDialog("krustyarrive")	--interrupted by krusty line. may fix. maybe not.
	Game.CloseStage()
	
	Game.AddStage()
		EnableCamera(8)
		Game.NoTrafficForStage()
		Game.SetStageAllowMissionCancel(0)
		Game.AddStageVehicle("krust_v","m5_krusty_billboard3-1","chase","Missions\\level01\\M5krusty.con", "krusty")
		Game.AddStageCharacter("bart", "m5_bart_cam8", "", "current", "m5_bart_billboard3")
		Game.AddObjective("timer")
			durationTime[Mode.NormalMode] = 2.5
			durationTime[Mode.HardMode] = 2.1
			Game.SetDurationTime(durationTime[Mode.Current])
		Game.CloseObjective()
		SurviveConditions()
		Game.StageStartMusicEvent("M5_start")
		Game.SetStageMusicAlwaysOn()
		Game.SetIrisWipe(0.1)
		Game.SetCompletionDialog("krustybetrayal")
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		Game.SetMaxTraffic(1)
		--SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(18)
		Game.SetHUDIcon("w_kbur2")
		Game.AddStageVehicle("krust_v","m5_krusty_billboard3-2","chase","Missions\\level01\\M5limo.con", "krusty")
		Game.AddStageCharacter("bart", "", "", "current", "m5_bart_billboard3")
		Game.AddObjective("goto")
			AddCrowdNPCs(3, "cletus", "nriviera", "joger1", "male4")
			Game.SetDestination("m5_crowd_kb","upwardglow")
		Game.CloseObjective()
		SetTimeByDifficulty(20, 15)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		Game.SetStageMessageIndex(20)
		Game.SetHUDIcon("w_pedm5")
		--Game.ActivateVehicle("krust_v", "NULL", "chase")
		Game.AddStageVehicle("krust_v","m5_krusty_kb","chase","Missions\\level01\\M5krusty.con", "krusty")
		Game.AddObjective("insidetrigger")
			AddCrowdNPCs(3, "cletus", "nriviera", "joger1", "male4")
			Game.SetObjTrigger("m5_crowd_kb_inside")
			Game.SetObjThreshold(10)
		Game.CloseObjective()
		Game.AddCondition("outsidetrigger")
			Game.SetCondMessageIndex(15)
			Game.SetCondTrigger("m5_crowd_kb_inside")
			Game.SetCondThreshold(outsideThreshold[Mode.Current])
			--Game.SetCondDecay(10, 1)
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		Game.SetHUDIcon( "w_krustc" )
		Game.SetStageMessageIndex(17)
		SetTrafficByDifficulty(3, 5)
		Game.AddStageVehicle("cPolic3", "m5_wiggum_firetruck", "NULL", "Missions\\level01\\M5wiggum.con", "wiggum")
		Game.ActivateVehicle("krust_v","NULL","chase")
		Game.AddObjective("losetail")
			AddCrowdNPCs(4, "busm1", "busm2", "busw1", "fem3")
			Game.SetObjTargetVehicle("krust_v")
			Game.SetObjDistance(150)
		Game.CloseObjective()
		SetTimeByDifficulty(60, 45)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	
	--[[
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(8)
		Game.SetHUDIcon("w_stad")
		Game.AddStageVehicle("krust_v","m5_krusty","NULL","Missions\\level01\\M5krusty.con", "krusty")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m5_krusty_chase_start","upwardglow")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.SetStageTime(30)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.SetCompletionDialog("krustybetrayal")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		SetTrafficByDifficulty(3, 5)
		Game.SetHUDIcon( "w_krustc" )
		Game.SetStageMessageIndex(17)
		Game.ActivateVehicle("krust_v","NULL","chase")
		Game.AddObjective("losetail")
			AddCrowdNPCs(4, "busm1", "busm2", "busw1", "fem3")
			Game.SetObjTargetVehicle("krust_v")
			Game.SetObjDistance(150)
		Game.CloseObjective()
		Game.SetStageTime(40)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	]]
	
	Game.AddStage()
		DisableAllCameras()
		NoBillboardChange()
		SetTrafficByDifficulty(3, 5)
		Game.SetStageMessageIndex(8)
		Game.SetHUDIcon("w_stad")
		Game.AddStageVehicle("cPolic3", "m5_wiggum_firetruck", "NULL", "Missions\\level01\\M5wiggum.con", "wiggum")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			AddCrowdNPCs(4, "busm1", "busm2", "busw1", "fem3")
			Game.SetDestination("m5_crowd_stadium","upwardglow")
		Game.CloseObjective()
		Game.SetStageTime(60)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
		Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage()
		EnableCamera(4)
		NoBillboardChange()
		Game.ResetStageHitAndRun()
		Game.NoTrafficForStage()
		Game.AddStageVehicle("cPolic3", "m5_wiggum_tunnel", "chase", "Missions\\level01\\M5wiggum.con", "wiggum")
		Game.AddStageCharacter("bart", "m5_bart_cam4", "", "current", "m5_bart_stadium")
		Game.AddObjective("timer")
			--AddCrowdNPCs(5, "busm1", "busm2", "busw1", "fem3")
			Game.SetDurationTime(2.5)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M5_start")
		Game.SetStageMusicAlwaysOn()
		Game.SetFadeOut(2)
		Game.SetCompletionDialog("barthitbycagain")
	Game.CloseStage()
	
	Game.AddStage()
		DisableAllCameras()
		Game.SetStageAllowMissionCancel(0)
		NoBillboardChange()
		Game.NoTrafficForStage()
		Game.AddStageVehicle("cPolic3", "m5_wiggum_car_talk", "NULL", "Missions\\level01\\M5wiggum.con")
		Game.AddStageCharacter("bart", "m5_bart_talk", "", "current", "m5_car_talk")
		Game.AddObjective("timer")
			Game.AddNPC("wiggum", "m5_wiggum_talk")
			Game.RemoveDriver("wiggum")
			Game.SetDurationTime(4.5)
			Game.StayInBlack()
		Game.CloseObjective()
		Game.SetMusicState("Mission7", "Silent")
		Game.StageStartMusicEvent("M7_start")
	Game.CloseStage()
	
	--[[
	Game.AddStage()
		--Game.SetStageAllowMissionCancel(0)
		NoBillboardChange()
		Game.NoTrafficForStage()
		Game.AddStageVehicle("cPolic3", "m5_wiggum_car_talk", "NULL", "Missions\\level01\\M5wiggum.con")
		Game.AddStageCharacter("bart", "m5_bart_talk", "", "current", "m5_car_talk")
		Game.AddObjective("timer")
			Game.AddNPC("wiggum", "m5_wiggum_talk")
			Game.SetDurationTime(2)
		Game.CloseObjective()
	Game.CloseStage()
	]]
	
	Game.AddStage()
		--Game.SetStageAllowMissionCancel(0)
		DisableAllCameras()
		NoBillboardChange()
		Game.NoTrafficForStage()
		Game.AddStageVehicle("cPolic3", "m5_wiggum_car_talk", "NULL", "Missions\\level01\\M5wiggum.con")
		Game.AddStageCharacter("bart", "m5_bart_talk", "", "current", "m5_car_talk")
		Game.AddObjective("dialogue")
			Game.AddNPC("wiggum", "m5_wiggum_talk")
			Game.AmbientAnimationRandomize( 1, 0 )
			Game.AmbientAnimationRandomize( 0, 0 )
			Game.SetConversationCam( 0, "pc_far" )
			Game.SetConversationCam( 1, "pc_near" )
			Game.AddAmbientNpcAnimation( "dialogue_shaking_fist" )
			Game.AddAmbientNpcAnimation( "dialogue_cross_arms" )
			Game.AddAmbientPcAnimation( "get_up" )
			Game.AddAmbientPcAnimation( "dialogue_hands_in_air" )
			Game.SetCamBestSide("m5_talk_bestside")
			Game.SetDialogueInfo("bart","wiggum","life",0)
			Game.SetDialoguePositions("m5_bart_talk","m5_wiggum_talk","m5_car_talk")
		Game.CloseObjective()
		--[[
		Game.AddObjective("timer")
			Game.AddNPC("wiggum", "m5_wiggum_talk")
			Game.SetDurationTime(3)
		Game.CloseObjective()
		]]
		--Game.SetIrisWipe(0.1)
		Game.SetCompletionDialog("life2")
	Game.CloseStage()
	
	Game.AddStage()
		Game.SetStageAllowMissionCancel(0)
		EnableCamera(5)
		NoBillboardChange()
		Game.NoTrafficForStage()
		Game.AddStageVehicle("homer_v", "m5_homer_town_hall", "evade", "Missions\\level01\\M5homer.con", "homer")
		Game.AddStageVehicle("cPolic3", "m5_wiggum_car_talk", "NULL", "Missions\\level01\\M5wiggum.con")
		Game.AddStageCharacter("bart", "m5_bart_cam5", "", "current", "m5_carstart")
		Game.AddStageWaypoint("m5_homer_path2-1")
		Game.AddObjective("timer")
			Game.SetDurationTime(3.5)
		Game.CloseObjective()
		Game.SetFadeOut(2)
		Game.SetCompletionDialog("wiggumhitbyc")
	Game.CloseStage()
	
	Game.AddStage()
		EnableCamera(6)
		Game.SetStageAllowMissionCancel(0)
		NoBillboardChange()
		Game.NoTrafficForStage()
		Game.AddStageVehicle("homer_v", "m5_homer_tovenue", "NULL", "Missions\\level01\\M5homer.con", "homer")
		Game.AddStageVehicle("cPolic3", "m5_wiggum_car_talk", "NULL", "Missions\\level01\\M5wiggum.con")
		Game.AddStageCharacter("bart", "m5_bart_cam6", "", "current", "m5_car_talk")
		Game.AddObjective("timer")
			Game.SetDurationTime(5.6)
			Game.StayInBlack()
		Game.CloseObjective()
		Game.SetCompletionDialog("homerleave","homer")
	Game.CloseStage()
	
	Game.AddStage()
		EnableCamera(6)
		Game.SetStageAllowMissionCancel(0)
		NoBillboardChange()
		Game.NoTrafficForStage()
		Game.AddStageVehicle("homer_v", "m5_homer_tovenue", "evade", "Missions\\level01\\M5homer.con", "homer")
		Game.AddStageVehicle("cPolic3", "m5_wiggum_tunnel", "evade", "Missions\\level01\\M5wiggum.con")
		Game.AddStageCharacter("bart", "m5_bart_cam6", "", "current", "m5_car_talk")
		Game.AddStageWaypoint("m5_venue_path1")
		Game.AddObjective("timer")
			Game.AddDriver("wiggum", "cPolic3")
			Game.RemoveNPC("wiggum")
			Game.SetDurationTime(7)
		Game.CloseObjective()
		--Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	--[[
	Game.AddStage()
		EnableCamera(6)
		Game.SetStageAllowMissionCancel(0)
		NoBillboardChange()
		Game.NoTrafficForStage()
		Game.AddStageVehicle("homer_v", "m5_bart_billboard1", "NULL", "Missions\\level01\\M5homer.con", "homer")
		Game.AddStageVehicle("cPolic3", "m5_homer_tovenue", "evade", "Missions\\level01\\M5wiggum.con")
		Game.AddStageCharacter("bart", "m5_bart_cam6", "", "current", "m5_car_talk")
		Game.AddStageWaypoint("m5_venue_path1")
		Game.AddObjective("timer")
			Game.SetDurationTime(4)
		Game.CloseObjective()
	Game.CloseStage()
	]]
	
	Game.AddStage("final")
		DisableAllCameras()
		NoBillboardChange()
		Game.SetMaxTraffic(5)
		--Game.AddStageCharacter("bart", "m5_bart_end", "", "current", "billboard_car")	--discourage players from using weak promotion vehicle
		Game.AddStageCharacter("bart", "m5_bart_end", "", "current", "m5_car_talk")	--or not. because mission select
		Game.AddObjective("timer")
			Game.SetDurationTime(1.5)
		Game.CloseObjective()
	Game.CloseStage()

Game.CloseMission()