Game.SelectMission("m5")

	Game.SetMissionResetPlayerInCar("m5_carstart")
	Game.SetDynaLoadData("l5z1.p3d;l5r1.p3d;l5r4.p3d;")

	Game.UsePedGroup(5)

	if Mode.IsNormal then
	Game.AddStage()
		Game.DisableTrigger("Poster1Loc")
		Game.DisableTrigger("Poster2Loc")
		Game.DisableTrigger("Poster3Loc")
		Game.SetStageMessageIndex(12)
		Game.AddObjective("getin")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
	Game.CloseStage()
	end
	
	Game.AddStage()
		Game.RESET_TO_HERE()
		Game.DisableTrigger("Poster1Loc")
		Game.DisableTrigger("Poster2Loc")
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetStageMessageIndex(03)
		Game.SetHUDIcon("w_train")
		Game.AddObjective("goto")
			Game.SetDestination("m5_trainyardFAKE","carsphere")
			Game.AddStageVehicle("moe_v","m5_moe_loc","NULL","Missions\\level01\\M0chase.con", "moe")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		if Mode.IsNormal then
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		end
		Game.SetStageTime(60)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
		Game.SetCompletionDialog("nobeer","moe")
	Game.CloseStage()
	

	Game.AddStage()
		Game.DisableTrigger("Poster1Loc")
		Game.DisableTrigger("Poster2Loc")
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetHUDIcon( "w_moecar" )
		Game.SetStageMessageIndex(04)
		Game.AddStageTime(-1)
		Game.ActivateVehicle("moe_v","NULL","chase")
		Game.AddObjective("losetail")
			Game.SetObjTargetVehicle("moe_v")
			if Mode.IsNormal then
			Game.SetObjDistance(150)
			else
			Game.SetObjDistance(160)
			end
		Game.CloseObjective()
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.SetCompletionDialog("notv","moe")
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster1Loc")
		Game.DisableTrigger("Poster2Loc")
		Game.DisableTrigger("Poster3Loc")
		Game.SetStageMessageIndex(03)
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetHUDIcon("w_train")
		Game.AddObjective("goto")
			Game.SetDestination("m5_trainyard","carsphere")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		if Mode.IsHard then
		Game.AddStageTime(15)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		end
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster1Loc")
		Game.DisableTrigger("Poster2Loc")
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetStageMessageIndex(09)
		Game.SetHUDIcon("w_billb1")
		Game.AddObjective("goto")
			Game.SetDestination("m5_poster2","triggersphere")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		if Mode.IsHard then
		Game.AddStageTime(-1)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		end
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster1Loc")
		Game.DisableTrigger("Poster2Loc")
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetStageMessageIndex(06)
		Game.SetHUDIcon("w_billb1")
		Game.AddObjective("insidetrigger")
			Game.SetObjTrigger("Poster2Obj")
			Game.SetObjThreshold(4)
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		if Mode.IsHard then
		Game.AddStageTime(-1)
		else
		Game.SetStageTime(15)
		end
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster1Loc")
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetStageMessageIndex(05)
		Game.SetHUDIcon("w_center")
		Game.AddObjective("goto")
			Game.SetDestination("m5_citycenter","carsphere")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.AddStageTime(40)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster1Loc")
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetStageMessageIndex(09)
		Game.SetHUDIcon("w_billb2")
		Game.AddStageTime(-1)
		Game.AddObjective("goto")
			Game.SetDestination("m5_poster1","triggersphere")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster1Loc")
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetStageMessageIndex(06)
		Game.SetHUDIcon("w_billb2")
		Game.AddObjective("insidetrigger")
			Game.SetObjTrigger("Poster1Obj")
			Game.SetObjThreshold(4)
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.AddStageTime(-1)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetStageMessageIndex(07)
		Game.SetHUDIcon("w_highwy")
		Game.AddObjective("goto")
			Game.SetDestination("m5_highway","carsphere")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.AddStageTime(55)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetStageMessageIndex(09)
		Game.SetHUDIcon("w_billb3")
		Game.AddStageTime(-1)
		Game.AddObjective("goto")
			Game.SetDestination("m5_poster3","triggersphere")
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("Poster3Loc")
		if Mode.IsNormal then
		Game.SetMaxTraffic(3)
		else
		Game.SetMaxTraffic(4)
		end
		Game.SetStageMessageIndex(06)
		Game.SetHUDIcon("w_billb3")
		Game.AddObjective("insidetrigger")
			Game.SetObjTrigger("Poster3Obj")
			Game.SetObjThreshold(4)
		Game.CloseObjective()
		Game.AddCondition( "damage" )
			Game.SetCondMinHealth( 0.0 )
			Game.SetCondTargetVehicle( "current" )
		Game.CloseCondition()
		Game.AddCondition("outofvehicle")
			Game.SetCondTime( 10000 )
		Game.CloseCondition()
		Game.AddStageTime(-1)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage("final")
		Game.StartCountdown("count")
		Game.AddToCountdownSequence( "o", 400 )
		Game.AddObjective("timer")
			Game.SetDurationTime(0.1)
		Game.CloseObjective()
	Game.CloseStage()

Game.CloseMission()