Game.SelectMission("m6")
	Game.SetMissionResetPlayerInCar("m6_car_sd")
	Game.SetDynaLoadData("l5r2.p3d;l5z2.p3d;l5r3.p3d;")

	Game.UsePedGroup(5)
	Game.SetNumValidFailureHints( Mode.FailHintCount )
	
	Game.StreetRacePropsUnload("m6_vandalism.p3d:")	--police station vandalism props

	if GetSetting("ScrapBookMode") then
		Game.AddStage()
			Game.CHECKPOINT_HERE()
			Game.SetCheckpointDynaLoadData("l5r3.p3d;l5z4.p3d;l5r4.p3d;")
			Game.SetCheckpointResetPlayerInCar("m6_restart1")
			Game.NoTrafficForStage()
			Game.AddStageVehicle("cArmor", "m6_armored_truck", "NULL", "Missions/level01/M6armor.con", "earhart")
			Game.AddStageVehicle("cPolice", "m6_cop_preview", "NULL", "Missions/level01/M6cop.con")
			Game.AddObjective("dummy")
			Game.CloseObjective()
		Game.CloseStage()
		Game.CloseMission()
		return
	end

	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.NoTrafficForStage()
		Game.SetStageMessageIndex(12)
		Game.AddObjective("getin")
			Game.SetObjTargetVehicle("current")
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.RESET_TO_HERE()
		ConstantHitAndRun(97)
		Game.SetNoHitAndRunMusicForStage()
		Game.SetStageNumChaseCars(1)
		Game.SetHUDIcon("w_save")
		Game.SetStageMessageIndex(18)
		SetTrafficByDifficulty(4, 5)
		Game.AddStageVehicle("cCube", "m6_prank_truck", "NULL", "Missions/level01/M6prank.con", "busm1")
		Game.AddObjective("goto")
			Game.SetDestination("m6_trynsave", "upwardglow")
		Game.CloseObjective()
		SetTimeByDifficulty(40, 30)
		Game.AddCondition("timeout")
		Game.CloseCondition()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		ConstantHitAndRun(100)
		Game.SetNoHitAndRunMusicForStage()
		Game.SetStageNumChaseCars(1)
		Game.SetHUDIcon("w_prank")
		Game.SetStageMessageIndex(19)
		SetTrafficByDifficulty(1, 3)	--i really don't know how to tweak this for Normal mode.
		Game.ActivateVehicle("cCube", "NULL", "target")
		Game.SetStageAITargetCatchupParams("cCube", 90, 110)
		Game.SetVehicleAIParams("cCube", -10, -9)
		for i = 1, 7 do
			Game.AddStageWaypoint("m6_pranktruck_nav" .. i)
		end
		Game.AddObjective("dump")
			--[[
			local itemList = {"stinkbomb", "eggs", "toiletroll"}
			local x = 1
			for i = 1, 12 do
				Game.AddCollectible("m6_prank" .. i, itemList[x])
				if x >= #itemList then
					x = 1
				else
					x = x + 1
				end
			end
			]]
			Game.AddCollectible("m6_prank1", "stinkbomb")
			Game.AddCollectible("m6_prank2", "eggs")
			Game.AddCollectible("m6_prank3", "toiletroll")
			Game.AddCollectible("m6_prank4", "stinkbomb")
			Game.AddCollectible("m6_prank5", "eggs")
			Game.AddCollectible("m6_prank6", "eggs")
			Game.AddCollectible("m6_prank7", "stinkbomb")
			Game.AddCollectible("m6_prank8", "eggs")
			Game.AddCollectible("m6_prank9", "toiletroll")
			Game.AddCollectible("m6_prank10", "stinkbomb")
			Game.SetObjTargetVehicle("cCube")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandruncaught")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_statio")
		Game.SetStageMessageIndex(20)
		SetTrafficByDifficulty(2,4)
		ConstantHitAndRun(100)
		Game.SetNoHitAndRunMusicForStage()
		Game.SetStageNumChaseCars(1)
		Game.AddStageVehicle("cArmor", "m6_armored_truck", "NULL", "Missions/level01/M6armor.con", "earhart")
		Game.AddObjective("goto")
			Game.SetDestination("m6_police_station_big", "upwardglow")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandruncaught")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage("locked", "car", "")
		Game.DisableTrigger("m6_cam1")
		ConstantHitAndRun(100)
		Game.SetNoHitAndRunMusicForStage()
		Game.SetStageNumChaseCars(1)
		Game.SetStageMessageIndex(11)
		Game.AddStageVehicle("cArmor", "m6_armored_truck", "NULL", "Missions/level01/M6armor.con", "earhart")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_cam1")
		ConstantHitAndRun(100)
		Game.SetNoHitAndRunMusicForStage()
		Game.SetStageNumChaseCars(1)
		Game.AddStageVehicle("cArmor", "m6_armored_truck", "NULL", "Missions/level01/M6armor.con", "earhart")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
		Game.ShowStageComplete()
	Game.CloseStage()
	
	Game.AddStage()
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointDynaLoadData("l5r3.p3d;l5z4.p3d;l5r4.p3d;")
		Game.SetCheckpointResetPlayerInCar("m6_restart1")
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		ConstantHitAndRun(100)
		Game.SetNoHitAndRunMusicForStage()
		Game.SetStageNumChaseCars(1)
		Game.SetHUDIcon("w_armor")
		Game.SetStageMessageIndex(21)
		--Game.SetMaxTraffic(1)
		SetTrafficByDifficulty(1, 4)
		Game.ActivateVehicle("cArmor", "NULL", "target")
		Game.SetStageAITargetCatchupParams("cArmor", 80, 90)
		for i = 1, 10 do
			Game.AddStageWaypoint("m6_armoredtruck_nav" .. i)
		end
		Game.AddObjective("dump")
			Game.AddCollectible("m6_prank1", "cellkey")
			Game.SetObjTargetVehicle("cArmor")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandruncaught")
		Game.CloseCondition()
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m6_fail")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_police")
		Game.SetStageMessageIndex(5)
		Game.SetStageHitAndRun(0)
		Game.SetStageHitAndRunDecay(30)
		Game.SetStageHitAndRunDecayHitAndRun(30)
		Game.SetStageHitAndRunFine(0)
		Game.SetStageNumChaseCars(1)
		Game.SetNoHitAndRunMusicForStage()
		Game.AddObjective("hitandrunlost")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandruncaught")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_statio")
		Game.SetStageMessageIndex(6)
		--Game.SetStageHitAndRun(0)
		Game.SetNoHitAndRunMusicForStage()
		SetTrafficByDifficulty(3, 5)
		Game.AddObjective("goto")
			Game.SetDestination("m6_police_station", "upwardglow")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_statio")
		Game.SetStageMessageIndex(22)
		Game.SetNoHitAndRunMusicForStage()
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m6_police_station_enter", "triggersphere")
			Game.MustActionTrigger()
		Game.CloseObjective()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
		Game.SetStageMusicAlwaysOn()
		Game.SetFadeOut(2)
		Game.SetCompletionDialog("breakout")
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableHitAndRun()
		Game.SetStageAllowMissionCancel(0)
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m6_bart_load_vandalism", "", "current", "m6_car_police")
		Game.NoTrafficForStage()
		Game.AddObjective("timer")
			Game.AddNPC("homer", "m6_homer_police")
			Game.SetDurationTime(1)
			Game.StayInBlack()
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableHitAndRun()
		Game.SetStageAllowMissionCancel(0)
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m6_bart_police", "", "current", "m6_car_police")
		Game.NoTrafficForStage()
		Game.AddObjective("timer")
			Game.AddNPC("homer", "m6_homer_police")
			Game.SetDurationTime(3)
			Game.StayInBlack()
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
		Game.SetCompletionDialog("homerthanks")
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableHitAndRun()
		Game.SetStageAllowMissionCancel(0)
		LockPlayer(9)
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "m6_bart_police", "", "current", "m6_car_police")
		Game.AddObjective("timer")
			Game.AddNPC("homer", "m6_homer_police")
			Game.SetDurationTime(4)
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage("locked", "car", "")
		Game.DisableHitAndRun()
		Game.SetStageAllowMissionCancel(0)
		LockPlayer(9)
		Game.SetStageMessageIndex(10)
		Game.AddObjective("timer")
			Game.AddNPC("homer", "m6_homer_police")
			Game.SetDurationTime(0)
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableHitAndRun()
		Game.SetStageAllowMissionCancel(0)
		LockPlayer(9)
		Game.AddObjective("timer")
			Game.AddNPC("homer", "m6_homer_police")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
		--Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage()
		Game.EnableHitAndRun()
		Game.SetStageMessageIndex(7)
		Game.SetStageHitAndRun(98)
		Game.SetStageHitAndRunDecay(0.0)
		Game.SetStageHitAndRunDecayHitAndRun(0.0)
		Game.SetStageHitAndRunDecayInterior(0.0)
		LockPlayer(9)
		Game.SetNoHitAndRunMusicForStage()
		SetTrafficByDifficulty(4, 5)
		Game.AddStageCharacter("bart", "", "", "current", "m6_car_police")
		Game.AddObjective("timer")
			Game.AddNPC("homer", "m6_homer_hide")
			Game.SetDurationTime(3.2)
		Game.CloseObjective()
		--if the player decides to get out and kick something during this stage, sucks to be them
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
		Game.ShowStageComplete()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.CHECKPOINT_HERE()
		Game.SetCheckpointResetPlayerInCar("m6_car_police")
		Game.SetCheckpointDynaLoadData("l5r3.p3d;l5z4.p3d;l5r4.p3d;m6_vandalism.p3d;")
		Game.EnableHitAndRun()
		Game.SetHUDIcon("w_stad2")
		Game.SetStageMessageIndex(9)
		SetTrafficByDifficulty(4, 5)
		local meterStart = {}
		local decay = {}
		meterStart[Mode.NormalMode] = 20
		meterStart[Mode.HardMode] = 22
		decay[Mode.NormalMode] = -0.4
		decay[Mode.HardMode] = -0.75
		Game.SetStageHitAndRun(meterStart[Mode.Current])
		Game.SetStageHitAndRunDecay(decay[Mode.Current])
		Game.SetStageHitAndRunDecayInterior(decay[Mode.Current])
		Game.SetStageHitAndRunDecayHitAndRun(-1)
		Game.SetNoHitAndRunMusicForStage()
		LockPlayer(0.0)
		Game.AddStageVehicle("cPolice", "m6_cop_car1", "NULL", "Missions/level01/M6cop.con")
		Game.AddObjective("goto")
			Game.SetDestination("m6_cop_trigger1", "upwardglow")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_police")
		Game.SetStageMessageIndex(13)
		Game.SetStageHitAndRunDecay(decay[Mode.Current])
		Game.SetStageHitAndRunDecayInterior(decay[Mode.Current])
		Game.SetStageHitAndRunDecayHitAndRun(-1)
		Game.SetNoHitAndRunMusicForStage()
		Game.ActivateVehicle("cPolice", "NULL", "target")
		Game.AddObjective("destroy")
			Game.SetObjTargetVehicle("cPolice")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
		Game.SetCompletionDialog("stinkbomb2")
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_stad3")
		Game.SetStageMessageIndex(10)
		Game.SetStageHitAndRunDecay(decay[Mode.Current])
		Game.SetStageHitAndRunDecayInterior(decay[Mode.Current])
		Game.SetStageHitAndRunDecayHitAndRun(-1)
		Game.SetNoHitAndRunMusicForStage()
		Game.AddStageVehicle("cPolice", "m6_cop_car2", "NULL", "Missions/level01/M6cop.con")
		Game.AddObjective("goto")
			Game.SetDestination("m6_cop_trigger2", "upwardglow")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_police")
		Game.SetStageMessageIndex(13)
		Game.SetStageHitAndRunDecay(decay[Mode.Current])
		Game.SetStageHitAndRunDecayInterior(decay[Mode.Current])
		Game.SetStageHitAndRunDecayHitAndRun(-1)
		Game.SetNoHitAndRunMusicForStage()
		Game.ActivateVehicle("cPolice", "NULL", "target")
		Game.AddObjective("destroy")
			Game.SetObjTargetVehicle("cPolice")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
		Game.SetCompletionDialog("stinkbomb")
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.EnableHitAndRun()
		Game.SetHUDIcon("w_java")
		Game.SetStageMessageIndex(11)
		Game.SetStageHitAndRunDecay(decay[Mode.Current])
		Game.SetStageHitAndRunDecayInterior(decay[Mode.Current])
		Game.SetStageHitAndRunDecayHitAndRun(-1)
		Game.SetNoHitAndRunMusicForStage()
		Game.AddStageVehicle("cPolice", "m6_cop_car3", "NULL", "Missions/level01/M6cop.con")
		Game.AddObjective("goto")
			Game.SetDestination("m6_cop_trigger3", "upwardglow")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_police")
		Game.SetStageMessageIndex(13)
		Game.SetStageHitAndRunDecay(decay[Mode.Current])
		Game.SetStageHitAndRunDecayInterior(decay[Mode.Current])
		Game.SetStageHitAndRunDecayHitAndRun(-1)
		Game.SetNoHitAndRunMusicForStage()
		Game.ActivateVehicle("cPolice", "NULL", "target")
		Game.AddObjective("destroy")
			Game.SetObjTargetVehicle("cPolice")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
		Game.SetCompletionDialog("stinkbomb")
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_lard")
		Game.SetStageMessageIndex(16)
		Game.SetStageHitAndRunDecay(decay[Mode.Current])
		Game.SetStageHitAndRunDecayInterior(decay[Mode.Current])
		Game.SetStageHitAndRunDecayHitAndRun(-1)
		Game.SetNoHitAndRunMusicForStage()
		Game.AddStageVehicle("cPolice", "m6_cop_car4", "NULL", "Missions/level01/M6cop.con")
		Game.AddObjective("goto")
			Game.SetDestination("m6_cop_trigger4", "upwardglow")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.SetHUDIcon("w_police")
		Game.SetStageMessageIndex(13)
		Game.SetStageHitAndRunDecay(decay[Mode.Current])
		Game.SetStageHitAndRunDecayInterior(decay[Mode.Current])
		Game.SetStageHitAndRunDecayHitAndRun(-1)
		Game.SetNoHitAndRunMusicForStage()
		Game.ActivateVehicle("cPolice", "NULL", "target")
		Game.AddObjective("destroy")
			Game.SetObjTargetVehicle("cPolice")
		Game.CloseObjective()
		SurviveConditions()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
		Game.SetCompletionDialog("stinkbomb3")
	Game.CloseStage()
	
	--reset h&r meter. can't do it if h&r is disabled.
	Game.AddStage()
		Game.ResetStageHitAndRun()
		Game.AddStageVehicle("cPolice", "m6_homer_hide", "NULL", "Missions/level01/M6cop.con")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableHitAndRun()
		Game.SetHUDIcon("w_hotel")
		Game.SetStageMessageIndex(14)
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		LockPlayer(0.016)	-- in case player destroyed last police car and got h&r simultaneously.
		Game.AddObjective("goto")
			Game.SetDestination("m6_venue_end", "upwardglow")
		Game.CloseObjective()
		SurviveConditions()
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableHitAndRun()
		Game.SetHUDIcon("w_hotel")
		Game.SetStageMessageIndex(17)
		Game.DisableTrigger("m6_remove_police_tape")
		Game.DisableTrigger("m6_cam1")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m7_hoteldoor", "triggersphere")
			Game.MustActionTrigger()
		Game.CloseObjective()
		Game.SetStageMusicAlwaysOn()
		Game.SetMusicState("Mission7", "Silent")
		Game.SetCompletionDialog("removetape")
		Game.SetFadeOut(2)
	Game.CloseStage()
	
	Game.AddStage()
		Game.DisableHitAndRun()
		Game.DisableTrigger("m6_add_venue_police_tape")
		--Game.AddStageCharacter("bart", "m6_bart_remove_tape", "", "current", "m7_car_sd")
		Game.AddStageCharacter("bart", "m6_bart_end", "", "current", "m7_car_sd")
		Game.AddObjective("timer")
			Game.SetDurationTime(1)
			Game.StayInBlack()
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_start")
	Game.CloseStage()
	
	Game.AddStage("final")
		Game.NoTrafficForStage()
		Game.EnableHitAndRun()	--why is this required to enable h&r for prior stages?
		Game.DisableTrigger("m6_add_venue_police_tape")
		Game.AddStageCharacter("bart", "m6_bart_end", "", "current", "m7_car_sd")
		Game.AddObjective("timer")
			Game.SetDurationTime(2)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_start")
	Game.CloseStage()
	
	--[[
	Game.AddStage()
		SetTrafficByDifficulty(4, 5)
		Game.AddObjective("dummy")
		Game.CloseObjective()
		Game.AddCondition("hitandrun")
		Game.CloseCondition()
	Game.CloseStage()
	]]

Game.CloseMission()