if GetSetting("TestM8") then
	dofile(Paths.Resources .. "/scripts/missions/level01/m8sdi.lua")
	return
end


local function DisableAllCameras()
	for i = 1, 5 do
	Game.DisableTrigger("m7_camera" .. i)
	end
end

local function EnableCamera(tableIndex)
	local CamToDisable = {1,2,3,4,5}
	table.remove(CamToDisable, tableIndex)
	for i, cam in ipairs(CamToDisable) do
		Game.DisableTrigger("m7_camera" .. cam)
	end
end

Game.SelectMission("m7sd")
	Game.SetMissionResetPlayerOutCar("m6_bart_sd","m7_car_sd")
	Game.SetDynaLoadData("l5r1.p3d;l5z2.p3d;l5r2.p3d;")
	Game.UsePedGroup(2)
	
	Game.StreetRacePropsUnload("m7_arena.p3d:m7_wrenchN.p3d:m7_wrenchH.p3d:MasterController*")
	
	Game.SetPedsEnabled(1)
	Game.SetParkedCarsEnabled(0)

	Game.SetHUDMapDrawable("l1hudmapShape")

	if GetSetting("ScrapBookMode") then
		Game.AddStage()
			Game.RESET_TO_HERE()
			DisableAllCameras()
			Game.DisableHitAndRun()
			Game.NoTrafficForStage()
			Game.AddStageVehicle("snake_v", "m7_snake_arena", "NULL", "Missions/level01/M7snake.con", "snake")
			Game.AddStageVehicle("cPolic3", "m7_wiggum_arena", "NULL", "Missions/level01/M7wiggum.con", "wiggum")
			Game.AddStageVehicle("krust_v", "m7_krusty_arena", "NULL", "Missions/level01/M7krusty.con", "krusty")
			Game.AddStageVehicle("cLimo2", "m7_limo_arena", "NULL", "Missions/level01/M7limo.con", "mobstr")
			Game.AddObjective("goto")
				Game.TurnGotoDialogOff()
				Game.SetDestination("m7_arena_start", "upwardglow")
				Game.SetCollectibleEffect("none")
			Game.CloseObjective()
		Game.CloseStage()
		
		Game.AddStage()
			EnableCamera(5)
			Game.DisableHitAndRun()
			Game.NoTrafficForStage()
			Game.AddStageVehicle("snake_v", "m7_snake_arena", "NULL", "Missions/level01/M7snake.con", "snake")
			Game.AddStageVehicle("cPolic3", "m7_wiggum_arena", "NULL", "Missions/level01/M7wiggum.con", "wiggum")
			Game.AddStageVehicle("krust_v", "m7_krusty_arena", "NULL", "Missions/level01/M7krusty.con", "krusty")
			Game.AddStageVehicle("cLimo2", "m7_limo_arena", "NULL", "Missions/level01/M7limo.con", "mobstr")
			Game.AddStageCharacter("bart", "m7_player_cam5", "", "current", "m7_bart_arena")
			Game.AddObjective("dummy")
			Game.CloseObjective()
		Game.CloseStage()
		Game.CloseMission()
		return
	end

	Game.AddStage()
		DisableAllCameras()
		Game.DisableHitAndRun()
		Game.SetHUDIcon("w_hotel")
		Game.SetStageMessageIndex(1)
		Game.SetMaxTraffic(5)
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m7_hotel", "upwardglow")
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		Game.RESET_TO_HERE()
		DisableAllCameras()
		Game.DisableHitAndRun()
		Game.SetHUDIcon("w_hotel")
		Game.SetStageMessageIndex(2)
		Game.SetMaxTraffic(5)
		Game.AddObjective("goto", "neither")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m7_hoteldoor", "triggersphere")
			Game.MustActionTrigger()
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		EnableCamera(1)
		Game.NoTrafficForStage()
		Game.DisableHitAndRun()
		Game.AddStageCharacter("bart", "m7_player_cam1", "", "current", "m7_car_sd")
		Game.AddStageVehicle("snake_v", "m7_snake_ambush", "evade", "Missions/level01/M7snake.con", "snake")
		Game.AddStageWaypoint("m7_snake_waypoint1")
		Game.AddStageWaypoint("m7_snake_waypoint2")
		Game.AddObjective("timer")
			Game.SetDurationTime(2.85)
		Game.CloseObjective()
		Game.SetCompletionDialog("snakeagain", "snake")
		Game.SetFadeOut(2)
	Game.CloseStage()

	Game.AddStage()
		EnableCamera(2)
		Game.DisableHitAndRun()
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "m7_player_cam2", "", "current", "m7_car_sd")
		Game.AddObjective("timer")
			Game.SetDurationTime(3)
			Game.StayInBlack()
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		EnableCamera(2)
		Game.DisableTrigger("z2_stairs")
		Game.DisableHitAndRun()
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "m7_player_cam2", "", "current", "m7_car_sd")
		Game.AddStageVehicle("snake_v", "m7_snake_leave", "evade", "Missions/level01/M7snake.con", "snake")
		Game.AddStageWaypoint("m7_snake_waypoint3")
		Game.AddObjective("timer")
			Game.SetDurationTime(3.75)
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage()
		DisableAllCameras()
		Game.DisableHitAndRun()
		Game.NoTrafficForStage()	--still no traffic here. they'll run into snake and wiggum.
		Game.SetHUDIcon("w_snakec")
		Game.SetStageMessageIndex(3)
		Game.AddStageVehicle("snake_v", "m7_snake_arena", "NULL", "Missions/level01/M7snake.con", "snake")
		Game.AddStageVehicle("cPolic3", "m7_wiggum_arena", "NULL", "Missions/level01/M7wiggum.con", "wiggum")
		Game.AddStageCharacter("bart", "m7_bart_getup", "", "current", "m7_car_sd")
		Game.AddObjective("goto")
			Game.TurnGotoDialogOff()
			Game.SetDestination("m7_arena_start", "upwardglow")
			Game.SetCollectibleEffect("none")
		Game.CloseObjective()
		Game.SetIrisWipe(0.1)
		Game.SetCompletionDialog("krustyarena")
	Game.CloseStage()

	Game.AddStage()
		EnableCamera(3)
		Game.DisableHitAndRun()
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "m7_player_cam3", "", "current", "m7_car_cam")
		Game.AddStageVehicle("krust_v", "m7_krusty_ambush", "evade", "Missions/level01/M7krusty.con", "krusty")
		Game.AddStageWaypoint("m7_ambush_waypoint")
		Game.AddObjective("timer")
			Game.SetDurationTime(3)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_drama")
		Game.SetStageMusicAlwaysOn()
		Game.SetCompletionDialog("limoarena")
	Game.CloseStage()

	Game.AddStage()
		EnableCamera(4)
		Game.DisableHitAndRun()
		Game.NoTrafficForStage()
		Game.AddStageCharacter("bart", "m7_player_cam4", "", "current", "m7_car_cam")
		Game.AddStageVehicle("cLimo2", "m7_limo_ambush", "evade", "Missions/level01/M7limo.con", "mobstr")
		Game.AddStageWaypoint("m7_ambush_waypoint")
		Game.AddObjective("timer")
			Game.SetDurationTime(4.25)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage()
		EnableCamera(5)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.NoTrafficForStage()
		Game.AddStageVehicle("snake_v", "m7_snake_arena", "NULL", "Missions/level01/M7snake.con", "snake")
		Game.AddStageVehicle("cPolic3", "m7_wiggum_arena", "NULL", "Missions/level01/M7wiggum.con", "wiggum")
		Game.AddStageVehicle("krust_v", "m7_krusty_arena", "NULL", "Missions/level01/M7krusty.con", "krusty")
		Game.AddStageVehicle("cLimo2", "m7_limo_arena", "NULL", "Missions/level01/M7limo.con", "mobstr")
		Game.AddStageCharacter("bart", "m7_player_cam5", "", "current", "m7_bart_arena")
		Game.AddStageVehicleCharacter( "current", "bart2", "dl" )
		Game.SetStageVehicleCharacterAnimation( "current", "bart2", "in_car_idle_driver" )
		Game.AddObjective("timer")
			Game.SetDurationTime(3)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_drama")
		Game.SetStageMusicAlwaysOn()
		Game.SetFadeOut(2)
	Game.CloseStage()

--[[
	Game.AddStage("locked", "car", "")
		EnableCamera(5)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.NoTrafficForStage()
		Game.SetStageMessageIndex(9)
		Game.AddStageVehicle("snake_v", "m7_snake_arena", "NULL", "Missions/level01/M7snake.con", "snake")
		Game.AddStageVehicle("cPolic3", "m7_wiggum_arena", "NULL", "Missions/level01/M7wiggum.con", "wiggum")
		Game.AddStageVehicle("krust_v", "m7_krusty_arena", "NULL", "Missions/level01/M7krusty.con", "krusty")
		Game.AddStageVehicle("cLimo2", "m7_limo_arena", "NULL", "Missions/level01/M7limo.con", "mobstr")
		Game.AddStageCharacter("bart", "m7_player_cam5", "", "current", "m7_bart_arena")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage("locked", "car", "")
		EnableCamera(5)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.NoTrafficForStage()
		Game.SetStageMessageIndex(10)
		Game.AddStageVehicle("snake_v", "m7_snake_arena", "NULL", "Missions/level01/M7snake.con", "snake")
		Game.AddStageVehicle("cPolic3", "m7_wiggum_arena", "NULL", "Missions/level01/M7wiggum.con", "wiggum")
		Game.AddStageVehicle("krust_v", "m7_krusty_arena", "NULL", "Missions/level01/M7krusty.con", "krusty")
		Game.AddStageVehicle("cLimo2", "m7_limo_arena", "NULL", "Missions/level01/M7limo.con", "mobstr")
		Game.AddStageCharacter("bart", "m7_player_cam5", "", "current", "m7_bart_arena")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage()
		EnableCamera(5)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.NoTrafficForStage()
		Game.AddStageVehicle("snake_v", "m7_snake_arena", "NULL", "Missions/level01/M7snake.con", "snake")
		Game.AddStageVehicle("cPolic3", "m7_wiggum_arena", "NULL", "Missions/level01/M7wiggum.con", "wiggum")
		Game.AddStageVehicle("krust_v", "m7_krusty_arena", "NULL", "Missions/level01/M7krusty.con", "krusty")
		Game.AddStageVehicle("cLimo2", "m7_limo_arena", "NULL", "Missions/level01/M7limo.con", "mobstr")
		Game.AddStageCharacter("bart", "m7_player_cam5", "", "current", "m7_bart_arena")
		Game.AddObjective("timer")
			Game.SetDurationTime(1)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_drama")
		Game.SetStageMusicAlwaysOn()
		Game.SetFadeOut(2)
	Game.CloseStage()
]]

	Game.AddStage()
		EnableCamera(5)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.NoTrafficForStage()
		Game.AddStageVehicle("snake_v", "m7_snake_arena", "NULL", "Missions/level01/M7snake.con", "snake")
		Game.AddStageVehicle("cPolic3", "m7_wiggum_arena", "NULL", "Missions/level01/M7wiggum.con", "wiggum")
		Game.AddStageVehicle("krust_v", "m7_krusty_arena", "NULL", "Missions/level01/M7krusty.con", "krusty")
		Game.AddStageVehicle("cLimo2", "m7_limo_arena", "NULL", "Missions/level01/M7limo.con", "mobstr")
		Game.AddStageCharacter("bart", "m7_player_loader", "", "current", "m7_bart_arena")
		Game.AddObjective("timer")
			Game.SetDurationTime(1)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage()
		EnableCamera(5)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.NoTrafficForStage()
		Game.AddStageVehicle("snake_v", "m7_snake_arena", "NULL", "Missions/level01/M7snake.con", "snake")
		Game.AddStageVehicle("cPolic3", "m7_wiggum_arena", "NULL", "Missions/level01/M7wiggum.con", "wiggum")
		Game.AddStageVehicle("krust_v", "m7_krusty_arena", "NULL", "Missions/level01/M7krusty.con", "krusty")
		Game.AddStageVehicle("cLimo2", "m7_limo_arena", "NULL", "Missions/level01/M7limo.con", "mobstr")
		Game.AddStageCharacter("bart", "m7_player_cam5", "", "current", "m7_bart_arena")
		Game.AddObjective("timer")
			Game.SetPresentationBitmap( "art/frontend/dynaload/images/mis01_07.p3d" )
			Game.SetDurationTime(3)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M7_drama")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	
	--replacement fadeout because of the game showing one frame of the arena despawning
	Game.AddStage()
		EnableCamera(5)
		Game.DisableHitAndRun()
		Game.AddObjective("fmv")
			Game.SetFMVInfo("..")
		Game.CloseObjective()
	Game.CloseStage()

Game.CloseMission()