local function DisableAllCameras()
	for i = 1, 4 do
	Game.DisableTrigger("m8_cam" .. i)
	end
end

local function EnableCamera(tableIndex)
	local CamToDisable = {1,2,3,4}
	table.remove(CamToDisable, tableIndex)
	for i, cam in ipairs(CamToDisable) do
		Game.DisableTrigger("m8_cam" .. cam)
	end
end

if GetSetting("TestM8") then
	Game.SelectMission("m7sd")
else
	Game.SelectMission("m8sd")
end
	Game.SetMissionResetPlayerOutCar("m8_bart_sd","m8_car_sd")
	Game.SetDynaLoadData("l5r1.p3d;l5z2.p3d;l5r2.p3d;")
	Game.UsePedGroup(2)

	--Game.StreetRacePropsLoad("missions/level01/l1_rewards.p3d:")
	Game.StreetRacePropsUnload("m8_fade.p3d:missions/level01/m8apu.p3d:")

	Game.SetPedsEnabled(0)
	Game.SetParkedCarsEnabled(1)

	Game.SetHUDMapDrawable("l1hudmapShape")

		Game.AddStage(0)
			DisableAllCameras()
			Game.DisableHitAndRun()
			--Game.SetHUDIcon("w_hotel")
			--Game.SetStageMessageIndex(2)
			Game.NoTrafficForStage()
			if GetSetting("TestM8") then
				Game.SetStageMessageIndex(7)
				Game.AddObjective("goto")
					Game.TurnGotoDialogOff()
					Game.SetDestination("m8_ending_test", "triggersphere")
					Game.SetCollectibleEffect("none")
					Game.MustActionTrigger()
			else
				Game.AddObjective("timer")
					Game.SetDurationTime(0)
			end
			Game.CloseObjective()
			Game.SetIrisWipe(0.1)
		Game.CloseStage()

	Game.AddStage(0)
		DisableAllCameras()
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m8_bart_venue", "", "current", "m8_car_venue")
		Game.AddObjective("timer")
			Game.SetDurationTime(1.5)
		Game.CloseObjective()
		Game.SetCompletionDialog("attenders1")
		Game.AddCondition("insidetrigger")
			Game.SetCondTrigger("m8_set_bonus_movie_flag")	--trigger is disabled if bonus mission isn't complete
			Game.SetCondThreshold(999)
			Game.SetCondDecay(0.1, 0)
			Game.SetCondDisplay("none")
			Game.SetCondSound("m8_set_bonus_movie_flag", "enter_trigger")	--sound is handled by lua script that enables bonus movie if trigger is enabled
		Game.CloseCondition()
	Game.CloseStage()

	Game.AddStage(0)
		EnableCamera(1)
		Game.DisableHitAndRun()
		Game.AddStageCharacter("bart", "m8_player_cam1", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_AI_R1", "evade", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_AI_R2", "evade", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_AI_R4", "evade", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_AI_R3", "evade", "Missions/level01/M8car1.con")
		--Game.AddStageVehicle("wagonA", "m8_AI_R5", "chase", "Missions/level01/M8car1.con")
		Game.AddStageWaypoint("m8_waypoint_R")
		Game.AddObjective("timer")
			Game.SetDurationTime(4.5)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
		Game.SetCompletionDialog("attenders2")
	Game.CloseStage()

	Game.AddStage(0)
		EnableCamera(2)
		Game.DisableHitAndRun()
		Game.AddStageCharacter("bart", "m8_player_cam2", "", "current", "m8_car_venue")
		Game.ActivateVehicle("compactA", "m8_AI_L4", "evade")
		Game.ActivateVehicle("sportsB", "m8_AI_L3", "evade")
		Game.ActivateVehicle("SUVA", "m8_AI_L4", "evade")
		Game.ActivateVehicle("pickupA", "m8_AI_L2", "evade")
		--Game.ActivateVehicle("wagonA", "m8_AI_L5", "chase")
		Game.AddStageWaypoint("m8_waypoint_L")
		Game.AddObjective("timer")
			Game.SetDurationTime(4)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
		Game.SetFadeOut(2)
	Game.CloseStage()

	--load apu if completed bm1. if player is using enzo, apu won't show up at all. fuck you, bonus car limit.
	Game.AddStage(0)
		DisableAllCameras()
		Game.DisableHitAndRun()
		Game.AddStageCharacter("bart", "m8_bart_load_apu", "", "current", "m8_car_venue")
		Game.AddObjective("timer")
			Game.SetDurationTime(0.5)
			Game.StayInBlack()
		Game.CloseObjective()
	Game.CloseStage()

	Game.AddStage(0)
		EnableCamera(3)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AddObjective("timer")
			Game.AddNPC("homer", "m8_npc1")
			Game.AddNPC("otto", "m8_npc2")
			Game.AddNPC("milhouse", "m8_npc3")
			Game.AddNPC("barney", "m8_npc4")
			Game.SetDurationTime(1.5)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
		--Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(3)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AddObjective("timer")
			Game.AddNPC("captain", "m8_npc5")
			Game.AddNPC("cletus", "m8_npc6")
			Game.AddNPC("nriviera", "m8_npc7")
			Game.AddNPC("cbg", "m8_npc8")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
		--Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(3)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AddObjective("timer")
			Game.AddNPC("ralph", "m8_npc9")
			Game.AddNPC("frink", "m8_npc10")
			Game.AddNPC("jimbo", "m8_npc11")
			Game.AddNPC("kearney", "m8_npc12")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
		--Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(3)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AddObjective("timer")
			Game.AddNPC("nelson", "m8_npc13")
			Game.AddNPC("carl", "m8_npc14")
			Game.AddNPC("lenny", "m8_npc15")
			Game.AddNPC("willie", "m8_npc16")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
		--Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(3)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AddObjective("timer")
			Game.AddNPC("fem1", "m8_npc17")
			Game.AddNPC("fem4", "m8_npc18")
			Game.AddNPC("beeman", "m8_npc19")
			Game.AddNPC("dolph", "m8_npc20")
			Game.SetDurationTime(0.5)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
		--Game.SetIrisWipe(0.1)
	Game.CloseStage()
	
	Game.AddStage(0)
		EnableCamera(3)
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AddObjective("timer")
			Game.AddNPC("male2", "m8_npc21")
			Game.AddNPC("male5", "m8_npc22")
			Game.AddNPC("bum", "m8_npc23")
			Game.AddNPC("male1", "m8_npc24")
			Game.SetDurationTime(4)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage(0)
		EnableCamera(3)
		Game.DisableHitAndRun()
		--Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AllowMissionAbort("false")
		Game.AddObjective("dialogue")
			Game.AddNPC("npd", "m8_npd_talk")
			Game.AmbientAnimationRandomize( 1, 0 )
			Game.AmbientAnimationRandomize( 0, 0 )
			Game.SetConversationCam( 0, "pc_far" )
			Game.SetConversationCam( 1, "npc_far" )
			Game.AddAmbientNpcAnimation( "none" )
			--Game.AddAmbientPcAnimation( "dialogue_shake_hand_in_air" )
			Game.AddAmbientPcAnimation( "victory_large" )
			Game.SetCamBestSide("m3_bestside")
			Game.SetDialogueInfo("bart","npd","welcome",0)
			Game.SetDialoguePositions("m8_bart_crowd","m8_npd_talk","m8_car_venue")
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage(0)
		DisableAllCameras()
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AddObjective("timer")
			Game.SetDurationTime(0)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()

	Game.AddStage(0)
		DisableAllCameras()
		Game.DisableHitAndRun()
		LockPlayer(9)
		Game.AddStageCharacter("bart", "m8_bart_venue", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AddObjective("camera")
			Game.SetObjCameraName("m8camShape")
			Game.SetObjMulticontName("CAM_m8camShape")
			Game.SetObjCanSkip(0)
			Game.SetObjNoLetterbox(1)
		Game.CloseObjective()
		Game.StageStartMusicEvent("M0_start")
		Game.SetStageMusicAlwaysOn()
	Game.CloseStage()
	--[[
	Game.AddStage(0)
		DisableAllCameras()
		Game.DisableHitAndRun()
		Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
		Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
		Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
		Game.AddObjective("dummy")
		Game.CloseObjective()
	Game.CloseStage()
	]]

	Game.AddStage(0)
		EnableCamera(4)
		LockPlayer(9)
		Game.AddObjective("fmv")
			Game.SetFMVInfo("final.rmv", "stopmusic")	--movie being handled by lua
		Game.CloseObjective()
	Game.CloseStage()
	
	if GetSetting("TestM8") then
		Game.AddStage(0)
			DisableAllCameras()
			Game.DisableHitAndRun()
			--Game.AddStageCharacter("bart", "m8_bart_crowd", "", "current", "m8_car_venue")
			Game.AddStageVehicle("compactA", "m8_parked1", "NULL", "Missions/level01/M8car1.con")
			Game.AddStageVehicle("sportsB", "m8_parked2", "NULL", "Missions/level01/M8car1.con")
			Game.AddStageVehicle("SUVA", "m8_parked3", "NULL", "Missions/level01/M8car1.con")
			Game.AddStageVehicle("pickupA", "m8_parked4", "NULL", "Missions/level01/M8car1.con")
			Game.AddStageVehicle("wagonA", "m8_parked5", "NULL", "Missions/level01/M8car1.con")
			Game.AddObjective("dummy")
			Game.CloseObjective()
		Game.CloseStage()
	end
	
	--enabling cam4 in this stage was intentional.
	--i don't want the camera going back to bart in the rare event that the black screen disappears (yes, it CAN happen).
 	Game.AddStage(0)
		EnableCamera(4)	
		Game.AddObjective("timer")
			Game.SetDurationTime(1.0)
			Game.SetGameOver()
		Game.CloseObjective()
	Game.CloseStage()
 
Game.CloseMission()